import type { Metadata } from 'next'

import { mapMemoryReview, type MemoryReviewListItem, type MemoryReviewRecord } from './memory-reviews/review-mappers'

const SITE_NAME = 'Couple Memory'

export type PublicPageKind = 'home' | 'photos' | 'timeline' | 'review' | 'topics'

export interface PublicSpaceMetadataSource {
  name: string
  slug: string
  bio: string | null
  coverPhotoUrl: string | null
  isPublic: boolean
}

export interface PublicSpacePageData extends PublicSpaceMetadataSource {
  id: string
  startDate: Date | null
}

export interface PublicNarrativeChapter {
  id: string
  title: string
  summary: string
}

export interface PublicNarrativeAlbum {
  id: string
  title: string
  description: string | null
  coverPhotoUrl: string | null
  chapters: PublicNarrativeChapter[]
}

export interface PublicPhotoItem {
  id: string
  displayUrl: string | null
  thumbnailUrl: string | null
  width: number | null
  height: number | null
  takenAt: string | null
  locationName: string | null
  aiCaption: string | null
  userCaption: string | null
  aiLayout: string
  aiMood: string | null
  album: { id: string; title: string }
}

export interface PublicTimelineItem {
  id: string
  title: string
  description: string | null
  date: string
  locationName: string | null
  isAutoGenerated: boolean
  photo: {
    id: string
    thumbnailUrl: string | null
    displayUrl: string | null
  } | null
}

export interface PublicReviewPair {
  yearlyReview: MemoryReviewListItem | null
  anniversaryReview: MemoryReviewListItem | null
}

export interface PublicFirstMoment {
  id: string
  title: string
  date: string | null
  locationName: string | null
  narrative: string
  imageUrl: string | null
}

export interface PublicFootprintLocation {
  locationName: string
  count: number
  firstDate: string | null
  lastDate: string | null
  imageUrl: string | null
}

type PublicNarrativeAlbumSource = {
  id: string
  title: string
  description: string | null
  coverPhotoUrl: string | null
  sortOrder: number
  chapters: Array<{
    id: string
    title: string
    aiSummary: string | null
    sortOrder: number
  }>
}

const pageConfig: Record<
  PublicPageKind,
  {
    path: (slug: string) => string
    title: (name: string) => string
    descriptionPrefix: (name: string) => string
  }
> = {
  home: {
    path: slug => `/s/${slug}`,
    title: name => `${name} | ${SITE_NAME}`,
    descriptionPrefix: () => '',
  },
  photos: {
    path: slug => `/s/${slug}/photos`,
    title: name => `${name} 的照片 | ${SITE_NAME}`,
    descriptionPrefix: name => `查看 ${name} 公开空间中的照片记录。`,
  },
  timeline: {
    path: slug => `/s/${slug}/timeline`,
    title: name => `${name} 的时间轴 | ${SITE_NAME}`,
    descriptionPrefix: name => `浏览 ${name} 公开空间的时间轴节点。`,
  },
  review: {
    path: slug => `/s/${slug}/review`,
    title: name => `${name} 的回顾 | ${SITE_NAME}`,
    descriptionPrefix: name => `阅读 ${name} 公开空间整理出的年度与周年回顾。`,
  },
  topics: {
    path: slug => `/s/${slug}/topics/firsts`,
    title: name => `${name} 的专题 | ${SITE_NAME}`,
    descriptionPrefix: name => `浏览 ${name} 公开空间整理出的专题内容与足迹总结。`,
  },
}

function buildDescription(
  page: PublicPageKind,
  space: PublicSpaceMetadataSource
) {
  const prefix = pageConfig[page].descriptionPrefix(space.name)
  const bio = space.bio?.trim()

  if (page === 'home') {
    return bio || `${space.name} 的公开情侣空间。`
  }

  return bio ? `${prefix}${bio}` : prefix
}

function buildFallbackMetadata(): Metadata {
  return {
    title: `页面不存在 | ${SITE_NAME}`,
    description: '你访问的公开空间不存在，或暂未公开。',
    robots: {
      index: false,
      follow: false,
    },
  }
}

export function buildPublicMetadata(
  space: PublicSpaceMetadataSource | null,
  page: PublicPageKind
): Metadata {
  if (!space || !space.isPublic) {
    return buildFallbackMetadata()
  }

  const path = pageConfig[page].path(space.slug)
  const title = pageConfig[page].title(space.name)
  const description = buildDescription(page, space)
  const images = space.coverPhotoUrl
    ? [{ url: space.coverPhotoUrl, alt: space.name }]
    : undefined

  return {
    title,
    description,
    alternates: {
      canonical: path,
    },
    openGraph: {
      title,
      description,
      url: path,
      siteName: SITE_NAME,
      type: 'website',
      images,
    },
    twitter: {
      card: space.coverPhotoUrl ? 'summary_large_image' : 'summary',
      title,
      description,
      images: space.coverPhotoUrl ? [space.coverPhotoUrl] : undefined,
    },
  }
}

export async function getPublicSpaceBySlug(slug: string) {
  const { prisma } = await import('./prisma')

  return prisma.couple.findUnique({
    where: { slug },
    select: {
      name: true,
      slug: true,
      bio: true,
      coverPhotoUrl: true,
      isPublic: true,
    },
  })
}

export async function getPublicSpacePageDataBySlug(
  slug: string
): Promise<PublicSpacePageData | null> {
  const { prisma } = await import('./prisma')

  return prisma.couple.findUnique({
    where: { slug },
    select: {
      id: true,
      name: true,
      slug: true,
      bio: true,
      coverPhotoUrl: true,
      isPublic: true,
      startDate: true,
    },
  })
}

export async function getPublicPhotosByCoupleId(
  coupleId: string
): Promise<PublicPhotoItem[]> {
  const { prisma } = await import('./prisma')
  const photos = await prisma.photo.findMany({
    where: {
      album: { coupleId },
      status: 'READY',
    },
    orderBy: [{ takenAt: 'desc' }, { createdAt: 'desc' }],
    select: {
      id: true,
      displayUrl: true,
      thumbnailUrl: true,
      width: true,
      height: true,
      takenAt: true,
      locationName: true,
      aiCaption: true,
      userCaption: true,
      aiLayout: true,
      aiMood: true,
      album: { select: { id: true, title: true } },
    },
  })

  return photos.map(photo => ({
    ...photo,
    takenAt: photo.takenAt?.toISOString() ?? null,
  }))
}

export async function getPublicTimelineByCoupleId(
  coupleId: string
): Promise<PublicTimelineItem[]> {
  const { prisma } = await import('./prisma')
  const milestones = await prisma.milestone.findMany({
    where: { coupleId },
    orderBy: { date: 'desc' },
    select: {
      id: true,
      title: true,
      description: true,
      date: true,
      locationName: true,
      isAutoGenerated: true,
      photo: {
        select: {
          id: true,
          thumbnailUrl: true,
          displayUrl: true,
        },
      },
    },
  })

  return milestones.map(milestone => ({
    ...milestone,
    date: milestone.date.toISOString(),
  }))
}

export async function getPublicMemoryReviewsByCoupleId(
  coupleId: string
): Promise<PublicReviewPair> {
  const { prisma } = await import('./prisma')
  const reviews = await prisma.memoryReview.findMany({
    where: {
      coupleId,
      status: 'READY',
      publishedAt: { not: null },
    },
    orderBy: [{ publishedAt: 'desc' }, { updatedAt: 'desc' }],
  }) as unknown as MemoryReviewRecord[]

  const items = reviews.map(mapMemoryReview)

  return {
    yearlyReview: items.find(review => review.type === 'YEARLY') ?? null,
    anniversaryReview:
      items.find(review => review.type === 'ANNIVERSARY') ?? null,
  }
}

export async function getPublicFirstMomentsByCoupleId(
  coupleId: string
): Promise<{
  firstMilestone: PublicFirstMoment | null
  firstPlace: PublicFirstMoment | null
  firstPhoto: PublicFirstMoment | null
}> {
  const { prisma } = await import('./prisma')

  const [milestones, photos] = await Promise.all([
    prisma.milestone.findMany({
      where: { coupleId },
      orderBy: [{ date: 'asc' }, { createdAt: 'asc' }],
      select: {
        id: true,
        title: true,
        description: true,
        date: true,
        locationName: true,
        photo: {
          select: {
            displayUrl: true,
            thumbnailUrl: true,
          },
        },
      },
    }),
    prisma.photo.findMany({
      where: {
        album: { coupleId },
        status: 'READY',
      },
      orderBy: [{ takenAt: 'asc' }, { createdAt: 'asc' }],
      select: {
        id: true,
        takenAt: true,
        createdAt: true,
        locationName: true,
        displayUrl: true,
        thumbnailUrl: true,
        userCaption: true,
        aiCaption: true,
      },
    }),
  ])

  const firstMilestone = milestones[0]
  const firstPlace = milestones.find(item => item.locationName?.trim())
  const firstPhoto = photos[0]

  return {
    firstMilestone: firstMilestone
      ? {
          id: firstMilestone.id,
          title: firstMilestone.title,
          date: firstMilestone.date.toISOString(),
          locationName: firstMilestone.locationName,
          narrative:
            firstMilestone.description?.trim() ||
            '这是最早被留下来的一个时间线节点。',
          imageUrl:
            firstMilestone.photo?.displayUrl ??
            firstMilestone.photo?.thumbnailUrl ??
            null,
        }
      : null,
    firstPlace: firstPlace
      ? {
          id: firstPlace.id,
          title: firstPlace.title,
          date: firstPlace.date.toISOString(),
          locationName: firstPlace.locationName,
          narrative:
            firstPlace.description?.trim() ||
            `这是最早和 ${firstPlace.locationName} 关联起来的一段回忆。`,
          imageUrl:
            firstPlace.photo?.displayUrl ??
            firstPlace.photo?.thumbnailUrl ??
            null,
        }
      : null,
    firstPhoto: firstPhoto
      ? {
          id: firstPhoto.id,
          title: firstPhoto.locationName?.trim() || '第一张公开照片',
          date: (firstPhoto.takenAt ?? firstPhoto.createdAt).toISOString(),
          locationName: firstPhoto.locationName,
          narrative:
            firstPhoto.userCaption?.trim() ||
            firstPhoto.aiCaption?.trim() ||
            '这是目前公开内容里最早的一张照片。',
          imageUrl: firstPhoto.displayUrl ?? firstPhoto.thumbnailUrl ?? null,
        }
      : null,
  }
}

export async function getPublicFootprintLocationsByCoupleId(
  coupleId: string
): Promise<PublicFootprintLocation[]> {
  const { prisma } = await import('./prisma')
  const photos = await prisma.photo.findMany({
    where: {
      album: { coupleId },
      status: 'READY',
      locationName: { not: null },
    },
    orderBy: [{ takenAt: 'asc' }, { createdAt: 'asc' }],
    select: {
      id: true,
      takenAt: true,
      createdAt: true,
      locationName: true,
      displayUrl: true,
      thumbnailUrl: true,
    },
  })

  const grouped = new Map<string, {
    locationName: string
    count: number
    firstDate: Date | null
    lastDate: Date | null
    imageUrl: string | null
  }>()

  for (const photo of photos) {
    const locationName = photo.locationName?.trim()
    if (!locationName) continue

    const date = photo.takenAt ?? photo.createdAt
    const existing = grouped.get(locationName)
    if (!existing) {
      grouped.set(locationName, {
        locationName,
        count: 1,
        firstDate: date,
        lastDate: date,
        imageUrl: photo.displayUrl ?? photo.thumbnailUrl ?? null,
      })
      continue
    }

    existing.count += 1
    if (!existing.firstDate || date.getTime() < existing.firstDate.getTime()) {
      existing.firstDate = date
    }
    if (!existing.lastDate || date.getTime() > existing.lastDate.getTime()) {
      existing.lastDate = date
    }
    if (!existing.imageUrl) {
      existing.imageUrl = photo.displayUrl ?? photo.thumbnailUrl ?? null
    }
  }

  return [...grouped.values()]
    .sort((left, right) => {
      if (right.count !== left.count) return right.count - left.count
      return (left.firstDate?.getTime() ?? 0) - (right.firstDate?.getTime() ?? 0)
    })
    .slice(0, 6)
    .map(item => ({
      locationName: item.locationName,
      count: item.count,
      firstDate: item.firstDate?.toISOString() ?? null,
      lastDate: item.lastDate?.toISOString() ?? null,
      imageUrl: item.imageUrl,
    }))
}

export function mapPublicNarrativeAlbums(
  albums: PublicNarrativeAlbumSource[]
): PublicNarrativeAlbum[] {
  return albums
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map(album => ({
      id: album.id,
      title: album.title,
      description: album.description,
      coverPhotoUrl: album.coverPhotoUrl,
      chapters: album.chapters
        .sort((a, b) => a.sortOrder - b.sortOrder)
        .map(chapter => ({
          id: chapter.id,
          title: chapter.title,
          summary: chapter.aiSummary?.trim() || '',
        }))
        .filter(chapter => chapter.summary.length > 0),
    }))
    .filter(album => Boolean(album.description?.trim()) || album.chapters.length > 0)
}

export async function getPublicNarrativeAlbumsByCoupleId(
  coupleId: string
): Promise<PublicNarrativeAlbum[]> {
  const { prisma } = await import('./prisma')
  const albums = await prisma.album.findMany({
    where: { coupleId },
    orderBy: [{ sortOrder: 'asc' }, { createdAt: 'asc' }],
    select: {
      id: true,
      title: true,
      description: true,
      coverPhotoUrl: true,
      sortOrder: true,
      chapters: {
        orderBy: [{ sortOrder: 'asc' }, { createdAt: 'asc' }],
        select: {
          id: true,
          title: true,
          aiSummary: true,
          sortOrder: true,
        },
      },
    },
  })

  return mapPublicNarrativeAlbums(albums)
}

export async function resolvePublicMetadata({
  slug,
  page,
  resolveSpace = getPublicSpaceBySlug,
}: {
  slug: string
  page: PublicPageKind
  resolveSpace?: (
    slug: string
  ) => Promise<PublicSpaceMetadataSource | null>
}): Promise<Metadata> {
  const space = await resolveSpace(slug)
  return buildPublicMetadata(space, page)
}
