import assert from 'node:assert/strict'
import test from 'node:test'

function createJsonRequest(url: string, body: unknown) {
  return new Request(`http://localhost${url}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
}

function createAuthContext(coupleId = 'couple_1') {
  return {
    userId: 'user_1',
    coupleUser: {
      coupleId,
    },
  } as never
}

test('createPatchMilestoneHandler updates only allowed milestone fields', async () => {
  const mod = await import('../../src/app/api/couples/[coupleId]/milestones/[milestoneId]/route')
  assert.equal(typeof mod.createPatchMilestoneHandler, 'function')

  let updateManyArgs: unknown

  const handler = mod.createPatchMilestoneHandler({
    prismaClient: {
      milestone: {
        updateMany: async (args: Record<string, unknown>) => {
          updateManyArgs = args
          return { count: 1 }
        },
        findUnique: async () => ({
          id: 'milestone_1',
          title: '第一次旅行',
          description: null,
          isAutoGenerated: false,
        }),
        deleteMany: async () => ({ count: 1 }),
      },
    } as never,
  })

  const response = await handler(
    createJsonRequest('/api/couples/couple_1/milestones/milestone_1', {
      title: ' 第一次旅行 ',
      description: '   ',
      isAutoGenerated: false,
      coupleId: 'other_couple',
    }),
    createAuthContext(),
    { coupleId: 'couple_1', milestoneId: 'milestone_1' }
  )

  assert.equal(response.status, 200)
  assert.deepEqual(updateManyArgs, {
    where: { id: 'milestone_1', coupleId: 'couple_1' },
    data: {
      title: '第一次旅行',
      description: null,
      isAutoGenerated: false,
    },
  })
})

test('createPatchMilestoneHandler returns 404 when milestone does not exist', async () => {
  const mod = await import('../../src/app/api/couples/[coupleId]/milestones/[milestoneId]/route')
  assert.equal(typeof mod.createPatchMilestoneHandler, 'function')

  const handler = mod.createPatchMilestoneHandler({
    prismaClient: {
      milestone: {
        updateMany: async () => ({ count: 0 }),
        findUnique: async () => null,
        deleteMany: async () => ({ count: 0 }),
      },
    } as never,
  })

  const response = await handler(
    createJsonRequest('/api/couples/couple_1/milestones/milestone_1', {
      isAutoGenerated: false,
    }),
    createAuthContext(),
    { coupleId: 'couple_1', milestoneId: 'milestone_1' }
  )

  assert.equal(response.status, 404)
  assert.deepEqual(await response.json(), { error: 'Not found' })
})
