import { NextResponse } from 'next/server'
import { withPublicAccess } from '@/lib/api-middleware'
import { prisma } from '@/lib/prisma'

export const GET = withPublicAccess(async (_req, { couple }) => {
  const milestones = await prisma.milestone.findMany({
    where: { coupleId: couple.id },
    orderBy: { date: 'desc' },
    select: {
      id: true,
      title: true,
      description: true,
      date: true,
      locationName: true,
      isAutoGenerated: true,
      photo: {
        select: {
          id: true,
          thumbnailUrl: true,
          displayUrl: true,
        },
      },
    },
  })

  return NextResponse.json({ milestones })
})
