'use client'

import { useState, useEffect } from 'react'
import { useLocale, useTranslations } from 'next-intl'

interface Milestone {
  id: string
  title: string
  description: string | null
  date: string
  locationName: string | null
  isAutoGenerated: boolean
  photoId: string | null
  photo: { thumbnailUrl: string | null } | null
}

type Translator = (key: string, values?: Record<string, string | number>) => string

export function buildTimelineUiText(t: Translator) {
  return {
    title: t('title'),
    create: t('create'),
    empty: t('empty'),
    reviewGenerated: t('reviewGenerated'),
    confirmGenerated: t('confirmGenerated'),
    confirmAllGenerated: t('confirmAllGenerated'),
    ignoreGenerated: t('ignoreGenerated'),
    relatedPhoto: t('relatedPhoto'),
    recommendationReason: t('recommendationReason'),
    mergeSuggestionTitle: t('mergeSuggestionTitle'),
    mergeSuggestionHint: t('mergeSuggestionHint'),
    mergeKeepPrimary: t('mergeKeepPrimary'),
    mergeRemoveDuplicate: t('mergeRemoveDuplicate'),
    pendingSection: t('pendingSection'),
    confirmedSection: t('confirmedSection'),
    pendingReview: (count: number) => t('pendingReview', { count }),
  }
}

export function buildTimelineMilestoneMeta({
  isAutoGenerated,
}: {
  isAutoGenerated: boolean
}) {
  return {
    showAiBadge: isAutoGenerated,
    needsReview: isAutoGenerated,
  }
}

export function buildTimelineReviewState(
  milestones: Array<{ isAutoGenerated: boolean }>
) {
  const pendingCount = milestones.filter(milestone => milestone.isAutoGenerated).length

  return {
    pendingCount,
    hasPending: pendingCount > 0,
  }
}

export function buildPendingGeneratedMilestoneIds(
  milestones: Array<{ id: string; isAutoGenerated: boolean }>
) {
  return milestones
    .filter(milestone => milestone.isAutoGenerated)
    .map(milestone => milestone.id)
}

export function buildTimelineSections<T extends { isAutoGenerated: boolean }>(milestones: T[]) {
  const pending = milestones.filter(milestone => milestone.isAutoGenerated)
  const confirmed = milestones.filter(milestone => !milestone.isAutoGenerated)

  return {
    pending,
    confirmed,
    hasPending: pending.length > 0,
  }
}

export function buildMilestoneRecommendationReason({
  isAutoGenerated,
  locationName,
  photoId,
}: {
  isAutoGenerated: boolean
  locationName: string | null
  photoId: string | null
}) {
  if (!isAutoGenerated) return ''
  if (locationName && photoId) {
    return '这条候选同时关联了地点和照片，适合作为一段回忆的清晰节点。'
  }
  if (locationName) {
    return `这条候选记录了地点“${locationName}”，适合你判断它是不是一次值得保留的阶段节点。`
  }
  if (photoId) {
    return '这条候选已经关联到具体照片，适合快速判断这是不是一段应该进入时间线的回忆。'
  }

  return '这条候选把一张可能重要的时刻提前提了出来，适合你快速确认是否值得留在时间线里。'
}

export function buildTimelineMergeSuggestions<T extends {
  id: string
  title: string
  date: string
  locationName: string | null
  isAutoGenerated: boolean
}>(milestones: T[]) {
  const confirmed = milestones.filter(milestone => !milestone.isAutoGenerated && milestone.locationName)
  const suggestions: Array<{
    primaryId: string
    primaryTitle: string
    duplicateId: string
    duplicateTitle: string
    locationName: string
    dateGapDays: number
  }> = []

  for (let i = 0; i < confirmed.length; i += 1) {
    const current = confirmed[i]!
    const currentDate = new Date(current.date)

    for (let j = i + 1; j < confirmed.length; j += 1) {
      const candidate = confirmed[j]!
      if (candidate.locationName !== current.locationName) continue

      const candidateDate = new Date(candidate.date)
      const dateGapDays = Math.round(
        Math.abs(candidateDate.getTime() - currentDate.getTime()) / (1000 * 60 * 60 * 24)
      )

      if (dateGapDays <= 3) {
        suggestions.push({
          primaryId: current.id,
          primaryTitle: current.title,
          duplicateId: candidate.id,
          duplicateTitle: candidate.title,
          locationName: current.locationName!,
          dateGapDays,
        })
        break
      }
    }
  }

  return suggestions
}

export default function TimelinePage() {
  const t = useTranslations('TimelinePage')
  const locale = useLocale()
  const [milestones, setMilestones] = useState<Milestone[]>([])
  const [coupleId, setCoupleId] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [showCreate, setShowCreate] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [refreshKey, setRefreshKey] = useState(0)

  useEffect(() => {
    async function fetchData() {
      const coupleRes = await fetch('/api/couples/mine')
      if (!coupleRes.ok) return setLoading(false)
      const couple = await coupleRes.json()
      setCoupleId(couple.id)

      const res = await fetch(`/api/couples/${couple.id}/milestones`)
      if (res.ok) {
        const data = await res.json()
        setMilestones(data.milestones)
      }
      setLoading(false)
    }
    fetchData()
  }, [refreshKey])

  async function handleCreate(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    if (!coupleId) return
    const formData = new FormData(e.currentTarget)

    const res = await fetch(`/api/couples/${coupleId}/milestones`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: formData.get('title'),
        description: formData.get('description') || undefined,
        date: formData.get('date'),
        locationName: formData.get('locationName') || undefined,
      }),
    })

    if (res.ok) {
      setShowCreate(false)
      setRefreshKey(k => k + 1)
    }
  }

  async function handleUpdate(e: React.FormEvent<HTMLFormElement>, id: string) {
    e.preventDefault()
    if (!coupleId) return
    const formData = new FormData(e.currentTarget)

    await fetch(`/api/couples/${coupleId}/milestones/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: formData.get('title'),
        description: formData.get('description') || null,
        date: formData.get('date'),
        locationName: formData.get('locationName') || null,
      }),
    })
    setEditingId(null)
    setRefreshKey(k => k + 1)
  }

  async function handleDelete(id: string) {
    if (!coupleId || !confirm(t('deleteConfirm'))) return
    await fetch(`/api/couples/${coupleId}/milestones/${id}`, { method: 'DELETE' })
    setRefreshKey(k => k + 1)
  }

  async function handleConfirmGenerated(id: string) {
    if (!coupleId) return

    await fetch(`/api/couples/${coupleId}/milestones/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        isAutoGenerated: false,
      }),
    })

    setRefreshKey(k => k + 1)
  }

  async function handleConfirmAllGenerated() {
    if (!coupleId) return

    const pendingIds = buildPendingGeneratedMilestoneIds(milestones)
    if (pendingIds.length === 0) return

    await Promise.all(
      pendingIds.map(id =>
        fetch(`/api/couples/${coupleId}/milestones/${id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            isAutoGenerated: false,
          }),
        })
      )
    )

    setRefreshKey(k => k + 1)
  }

  if (loading) return <TimelineSkeleton />
  const uiText = buildTimelineUiText(t)
  const reviewState = buildTimelineReviewState(milestones)
  const sections = buildTimelineSections(milestones)
  const mergeSuggestions = buildTimelineMergeSuggestions(milestones)

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold text-warm-text">{uiText.title}</h1>
          {reviewState.hasPending ? (
            <div className="flex flex-wrap items-center gap-3">
              <p className="text-sm text-info">{uiText.pendingReview(reviewState.pendingCount)}</p>
              <button
                type="button"
                onClick={handleConfirmAllGenerated}
                className="px-2.5 py-1 text-xs text-info border border-info/30 rounded-[var(--radius-sm)]
                  hover:bg-info/10 transition-colors"
              >
                {uiText.confirmAllGenerated}
              </button>
            </div>
          ) : null}
        </div>
        <button
          onClick={() => setShowCreate(true)}
          className="px-4 py-2 text-sm bg-warm-accent text-white rounded-[var(--radius-md)] font-medium
            hover:bg-warm-accent-hover transition-colors"
        >
          {uiText.create}
        </button>
      </div>

      {mergeSuggestions.length > 0 ? (
        <section className="mb-6 rounded-[var(--radius-lg)] border border-warm-border bg-warm-surface p-4">
          <h2 className="text-sm font-semibold text-warm-text">{uiText.mergeSuggestionTitle}</h2>
          <div className="mt-3 space-y-3">
            {mergeSuggestions.map(suggestion => (
              <div
                key={`${suggestion.primaryId}:${suggestion.duplicateId}`}
                className="rounded-[var(--radius-md)] border border-warm-border bg-warm-bg px-3 py-3"
              >
                <p className="text-sm text-warm-muted">
                  {uiText.mergeSuggestionHint.replace('{location}', suggestion.locationName).replace('{days}', String(suggestion.dateGapDays))}
                </p>
                <div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-warm-text">
                  <span className="rounded-full bg-success/10 px-2.5 py-1 text-success">
                    {uiText.mergeKeepPrimary}: {suggestion.primaryTitle}
                  </span>
                  <span className="rounded-full bg-warm-surface px-2.5 py-1">
                    {uiText.mergeRemoveDuplicate}: {suggestion.duplicateTitle}
                  </span>
                </div>
                <div className="mt-3">
                  <button
                    type="button"
                    onClick={() => void handleDelete(suggestion.duplicateId)}
                    className="px-3 py-1.5 text-sm text-warm-text border border-warm-border rounded-[var(--radius-sm)]
                      hover:bg-warm-surface transition-colors"
                  >
                    {uiText.mergeRemoveDuplicate}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      {milestones.length === 0 ? (
        <div className="text-center py-20 bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border">
          <p className="text-warm-muted mb-4">{uiText.empty}</p>
          <button
            onClick={() => setShowCreate(true)}
            className="px-4 py-2 text-sm text-warm-accent border border-warm-accent
              rounded-[var(--radius-md)] hover:bg-warm-accent/10 transition-colors"
          >
            {t('createFirst')}
          </button>
        </div>
      ) : (
        <div className="relative">
          {/* 时间线竖线 */}
          <div className="absolute left-6 top-0 bottom-0 w-px bg-warm-border" />

          <div className="space-y-8">
            {sections.pending.length > 0 ? (
              <section className="space-y-4">
                <div className="pl-14">
                  <h2 className="text-sm font-semibold uppercase tracking-[0.18em] text-info">
                    {uiText.pendingSection}
                  </h2>
                </div>
                {sections.pending.map(m => (
                  <MilestoneCard
                    key={m.id}
                    milestone={m}
                    locale={locale}
                    editingId={editingId}
                    setEditingId={setEditingId}
                    handleUpdate={handleUpdate}
                    handleDelete={handleDelete}
                    handleConfirmGenerated={handleConfirmGenerated}
                    inputClass={inputClass}
                    t={t}
                    uiText={uiText}
                  />
                ))}
              </section>
            ) : null}

            {sections.confirmed.length > 0 ? (
              <section className="space-y-4">
                <div className="pl-14">
                  <h2 className="text-sm font-semibold uppercase tracking-[0.18em] text-warm-muted">
                    {uiText.confirmedSection}
                  </h2>
                </div>
                {sections.confirmed.map(m => (
                  <MilestoneCard
                    key={m.id}
                    milestone={m}
                    locale={locale}
                    editingId={editingId}
                    setEditingId={setEditingId}
                    handleUpdate={handleUpdate}
                    handleDelete={handleDelete}
                    handleConfirmGenerated={handleConfirmGenerated}
                    inputClass={inputClass}
                    t={t}
                    uiText={uiText}
                  />
                ))}
              </section>
            ) : null}
          </div>
        </div>
      )}

      {/* 创建弹窗 */}
      {showCreate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-black/30" onClick={() => setShowCreate(false)} />
          <div className="relative bg-warm-surface rounded-[var(--radius-xl)] shadow-2xl p-6 w-full max-w-md mx-4">
            <h2 className="text-lg font-bold text-warm-text mb-4">{t('createTitle')}</h2>
            <form onSubmit={handleCreate} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldTitle')}</label>
                <input name="title" required autoFocus className={inputClass} placeholder={t('fieldTitlePlaceholder')} />
              </div>
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldDate')}</label>
                <input name="date" type="date" required className={inputClass} />
              </div>
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldLocation')}</label>
                <input name="locationName" className={inputClass} placeholder={t('fieldLocationPlaceholder')} />
              </div>
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldDescription')}</label>
                <textarea name="description" rows={2} className={inputClass + ' resize-none'} placeholder={t('fieldDescriptionPlaceholder')} />
              </div>
              <div className="flex gap-3 pt-2">
                <button type="button" onClick={() => setShowCreate(false)}
                  className="flex-1 py-2.5 text-sm text-warm-muted border border-warm-border rounded-[var(--radius-md)] hover:bg-warm-bg transition-colors">
                  {t('cancel')}
                </button>
                <button type="submit"
                  className="flex-1 py-2.5 text-sm bg-warm-accent text-white font-medium rounded-[var(--radius-md)] hover:bg-warm-accent-hover transition-colors">
                  {t('submit')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

const inputClass = `w-full px-4 py-2.5 rounded-[var(--radius-md)] border border-warm-border
  bg-warm-bg text-warm-text placeholder:text-warm-muted/60
  focus:ring-2 focus:ring-warm-accent/30 focus:border-warm-accent outline-none
  transition-all duration-200 text-sm`

function TimelineSkeleton() {
  return (
    <div className="animate-pulse">
      <div className="flex justify-between mb-6">
        <div className="h-8 bg-warm-border rounded w-24" />
        <div className="h-9 bg-warm-border rounded w-28" />
      </div>
      <div className="space-y-4 pl-14">
        {[1, 2, 3].map(i => (
          <div key={i} className="bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border p-5">
            <div className="h-5 bg-warm-border rounded w-1/3 mb-2" />
            <div className="h-4 bg-warm-border rounded w-2/3 mb-2" />
            <div className="h-3 bg-warm-border rounded w-1/4" />
          </div>
        ))}
      </div>
    </div>
  )
}

function MilestoneCard({
  milestone: m,
  locale,
  editingId,
  setEditingId,
  handleUpdate,
  handleDelete,
  handleConfirmGenerated,
  inputClass,
  t,
  uiText,
}: {
  milestone: Milestone
  locale: string
  editingId: string | null
  setEditingId: (id: string | null) => void
  handleUpdate: (e: React.FormEvent<HTMLFormElement>, id: string) => Promise<void>
  handleDelete: (id: string) => Promise<void>
  handleConfirmGenerated: (id: string) => Promise<void>
  inputClass: string
  t: ReturnType<typeof useTranslations<'TimelinePage'>>
  uiText: ReturnType<typeof buildTimelineUiText>
}) {
  const meta = buildTimelineMilestoneMeta({ isAutoGenerated: m.isAutoGenerated })

  return (
    <div className="relative pl-14">
      <div className={`absolute left-[18px] top-5 h-5 w-5 rounded-full border-2 ${
        m.isAutoGenerated
          ? 'border-info bg-info/20'
          : 'border-warm-accent bg-warm-accent/20'
      }`}
      />

      <div className="bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border p-5">
        {editingId === m.id ? (
          <form onSubmit={e => handleUpdate(e, m.id)} className="space-y-3">
            <input name="title" defaultValue={m.title} required className={inputClass} />
            <textarea name="description" defaultValue={m.description || ''} rows={2} className={inputClass + ' resize-none'} />
            <div className="flex gap-3">
              <input name="date" type="date" defaultValue={m.date.split('T')[0]} required className={inputClass + ' flex-1'} />
              <input name="locationName" defaultValue={m.locationName || ''} placeholder={t('locationPlaceholder')} className={inputClass + ' flex-1'} />
            </div>
            <div className="flex gap-2">
              <button type="submit" className="px-3 py-1.5 text-xs bg-warm-accent text-white rounded-[var(--radius-sm)]">{t('save')}</button>
              <button type="button" onClick={() => setEditingId(null)} className="px-3 py-1.5 text-xs text-warm-muted border border-warm-border rounded-[var(--radius-sm)]">{t('cancel')}</button>
            </div>
          </form>
        ) : (
          <div className="flex items-start justify-between gap-3">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <h3 className="font-semibold text-warm-text">{m.title}</h3>
                {meta.showAiBadge ? (
                  <span className="px-1.5 py-0.5 text-[10px] text-info bg-info/10 rounded">
                    {t('aiGenerated')}
                  </span>
                ) : null}
              </div>
              {m.description ? (
                <p className="text-sm text-warm-muted mt-1">{m.description}</p>
              ) : null}
              {meta.needsReview ? (
                <p className="mt-2 text-sm text-info">
                  {uiText.recommendationReason}: {buildMilestoneRecommendationReason({
                    isAutoGenerated: m.isAutoGenerated,
                    locationName: m.locationName,
                    photoId: m.photoId,
                  })}
                </p>
              ) : null}
              <div className="flex flex-wrap gap-3 mt-2 text-xs text-warm-muted">
                <span>{new Date(m.date).toLocaleDateString(locale, {
                  year: 'numeric', month: 'long', day: 'numeric',
                })}
                </span>
                {m.locationName ? <span>{m.locationName}</span> : null}
                {m.photo ? <span>{uiText.relatedPhoto}</span> : null}
              </div>
            </div>

            <div className="flex items-center gap-1 flex-shrink-0">
              {m.photo?.thumbnailUrl ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={m.photo.thumbnailUrl}
                  alt=""
                  className="w-12 h-12 rounded-[var(--radius-sm)] object-cover"
                />
              ) : null}
              <button
                onClick={() => handleConfirmGenerated(m.id)}
                className="px-2 py-1 text-[11px] text-info border border-info/30 rounded-[var(--radius-sm)]
                  hover:bg-info/10 transition-colors"
                disabled={!meta.needsReview}
                title={uiText.confirmGenerated}
              >
                {uiText.confirmGenerated}
              </button>
              {meta.needsReview ? (
                <button
                  onClick={() => handleDelete(m.id)}
                  className="px-2 py-1 text-[11px] text-warm-muted border border-warm-border rounded-[var(--radius-sm)]
                    hover:bg-warm-bg transition-colors"
                  title={uiText.ignoreGenerated}
                >
                  {uiText.ignoreGenerated}
                </button>
              ) : null}
              <button
                onClick={() => setEditingId(m.id)}
                className="p-1.5 text-warm-muted hover:text-warm-text rounded transition-colors"
                title={t('editTitle')}
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                  <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                </svg>
              </button>
              {!meta.needsReview ? (
                <button
                  onClick={() => handleDelete(m.id)}
                  className="p-1.5 text-warm-muted hover:text-error rounded transition-colors"
                  title={t('deleteTitle')}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polyline points="3 6 5 6 21 6" />
                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                  </svg>
                </button>
              ) : null}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
