'use client'

import { useState, useEffect, useCallback } from 'react'

interface Milestone {
  id: string
  title: string
  description: string | null
  date: string
  locationName: string | null
  isAutoGenerated: boolean
  photoId: string | null
  photo: { thumbnailUrl: string | null } | null
}

export default function TimelinePage() {
  const [milestones, setMilestones] = useState<Milestone[]>([])
  const [coupleId, setCoupleId] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [showCreate, setShowCreate] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)

  const fetchData = useCallback(async () => {
    const coupleRes = await fetch('/api/couples/mine')
    if (!coupleRes.ok) return setLoading(false)
    const couple = await coupleRes.json()
    setCoupleId(couple.id)

    const res = await fetch(`/api/couples/${couple.id}/milestones`)
    if (res.ok) {
      const data = await res.json()
      setMilestones(data.milestones)
    }
    setLoading(false)
  }, [])

  useEffect(() => { fetchData() }, [fetchData])

  async function handleCreate(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    if (!coupleId) return
    const formData = new FormData(e.currentTarget)

    const res = await fetch(`/api/couples/${coupleId}/milestones`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: formData.get('title'),
        description: formData.get('description') || undefined,
        date: formData.get('date'),
        locationName: formData.get('locationName') || undefined,
      }),
    })

    if (res.ok) {
      setShowCreate(false)
      fetchData()
    }
  }

  async function handleUpdate(e: React.FormEvent<HTMLFormElement>, id: string) {
    e.preventDefault()
    if (!coupleId) return
    const formData = new FormData(e.currentTarget)

    await fetch(`/api/couples/${coupleId}/milestones/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: formData.get('title'),
        description: formData.get('description') || null,
        date: formData.get('date'),
        locationName: formData.get('locationName') || null,
      }),
    })
    setEditingId(null)
    fetchData()
  }

  async function handleDelete(id: string) {
    if (!coupleId || !confirm('确定删除此里程碑？')) return
    await fetch(`/api/couples/${coupleId}/milestones/${id}`, { method: 'DELETE' })
    fetchData()
  }

  if (loading) return <TimelineSkeleton />

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-warm-text">时间轴</h1>
        <button
          onClick={() => setShowCreate(true)}
          className="px-4 py-2 text-sm bg-warm-accent text-white rounded-[var(--radius-md)] font-medium
            hover:bg-warm-accent-hover transition-colors"
        >
          添加里程碑
        </button>
      </div>

      {milestones.length === 0 ? (
        <div className="text-center py-20 bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border">
          <p className="text-warm-muted mb-4">还没有里程碑</p>
          <button
            onClick={() => setShowCreate(true)}
            className="px-4 py-2 text-sm text-warm-accent border border-warm-accent
              rounded-[var(--radius-md)] hover:bg-warm-accent/10 transition-colors"
          >
            添加第一个里程碑
          </button>
        </div>
      ) : (
        <div className="relative">
          {/* 时间线竖线 */}
          <div className="absolute left-6 top-0 bottom-0 w-px bg-warm-border" />

          <div className="space-y-6">
            {milestones.map(m => (
              <div key={m.id} className="relative pl-14">
                {/* 时间点圆圈 */}
                <div className={`absolute left-[18px] top-5 w-5 h-5 rounded-full border-2
                  ${m.isAutoGenerated
                    ? 'border-info bg-info/20'
                    : 'border-warm-accent bg-warm-accent/20'
                  }`}
                />

                <div className="bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border p-5">
                  {editingId === m.id ? (
                    <form onSubmit={e => handleUpdate(e, m.id)} className="space-y-3">
                      <input
                        name="title"
                        defaultValue={m.title}
                        required
                        className={inputClass}
                      />
                      <textarea
                        name="description"
                        defaultValue={m.description || ''}
                        rows={2}
                        className={inputClass + ' resize-none'}
                      />
                      <div className="flex gap-3">
                        <input
                          name="date"
                          type="date"
                          defaultValue={m.date.split('T')[0]}
                          required
                          className={inputClass + ' flex-1'}
                        />
                        <input
                          name="locationName"
                          defaultValue={m.locationName || ''}
                          placeholder="地点"
                          className={inputClass + ' flex-1'}
                        />
                      </div>
                      <div className="flex gap-2">
                        <button type="submit" className="px-3 py-1.5 text-xs bg-warm-accent text-white rounded-[var(--radius-sm)]">保存</button>
                        <button type="button" onClick={() => setEditingId(null)} className="px-3 py-1.5 text-xs text-warm-muted border border-warm-border rounded-[var(--radius-sm)]">取消</button>
                      </div>
                    </form>
                  ) : (
                    <>
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1">
                            <h3 className="font-semibold text-warm-text">{m.title}</h3>
                            {m.isAutoGenerated && (
                              <span className="px-1.5 py-0.5 text-[10px] text-info bg-info/10 rounded">
                                AI 生成
                              </span>
                            )}
                          </div>
                          {m.description && (
                            <p className="text-sm text-warm-muted mt-1">{m.description}</p>
                          )}
                          <div className="flex flex-wrap gap-3 mt-2 text-xs text-warm-muted">
                            <span>{new Date(m.date).toLocaleDateString('zh-CN', {
                              year: 'numeric', month: 'long', day: 'numeric',
                            })}</span>
                            {m.locationName && <span>{m.locationName}</span>}
                          </div>
                        </div>

                        <div className="flex items-center gap-1 flex-shrink-0">
                          {m.photo?.thumbnailUrl && (
                            <img
                              src={m.photo.thumbnailUrl}
                              alt=""
                              className="w-12 h-12 rounded-[var(--radius-sm)] object-cover"
                            />
                          )}
                          <button
                            onClick={() => setEditingId(m.id)}
                            className="p-1.5 text-warm-muted hover:text-warm-text rounded transition-colors"
                            title="编辑"
                          >
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                            </svg>
                          </button>
                          <button
                            onClick={() => handleDelete(m.id)}
                            className="p-1.5 text-warm-muted hover:text-error rounded transition-colors"
                            title="删除"
                          >
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <polyline points="3 6 5 6 21 6" />
                              <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                            </svg>
                          </button>
                        </div>
                      </div>
                    </>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 创建弹窗 */}
      {showCreate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-black/30" onClick={() => setShowCreate(false)} />
          <div className="relative bg-warm-surface rounded-[var(--radius-xl)] shadow-2xl p-6 w-full max-w-md mx-4">
            <h2 className="text-lg font-bold text-warm-text mb-4">添加里程碑</h2>
            <form onSubmit={handleCreate} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">标题</label>
                <input name="title" required autoFocus className={inputClass} placeholder="里程碑名称" />
              </div>
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">日期</label>
                <input name="date" type="date" required className={inputClass} />
              </div>
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">地点（可选）</label>
                <input name="locationName" className={inputClass} placeholder="例如：广州·珠江新城" />
              </div>
              <div>
                <label className="block text-sm font-medium text-warm-text mb-1.5">描述（可选）</label>
                <textarea name="description" rows={2} className={inputClass + ' resize-none'} placeholder="记录这个特别的时刻..." />
              </div>
              <div className="flex gap-3 pt-2">
                <button type="button" onClick={() => setShowCreate(false)}
                  className="flex-1 py-2.5 text-sm text-warm-muted border border-warm-border rounded-[var(--radius-md)] hover:bg-warm-bg transition-colors">
                  取消
                </button>
                <button type="submit"
                  className="flex-1 py-2.5 text-sm bg-warm-accent text-white font-medium rounded-[var(--radius-md)] hover:bg-warm-accent-hover transition-colors">
                  创建
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

const inputClass = `w-full px-4 py-2.5 rounded-[var(--radius-md)] border border-warm-border
  bg-warm-bg text-warm-text placeholder:text-warm-muted/60
  focus:ring-2 focus:ring-warm-accent/30 focus:border-warm-accent outline-none
  transition-all duration-200 text-sm`

function TimelineSkeleton() {
  return (
    <div className="animate-pulse">
      <div className="flex justify-between mb-6">
        <div className="h-8 bg-warm-border rounded w-24" />
        <div className="h-9 bg-warm-border rounded w-28" />
      </div>
      <div className="space-y-4 pl-14">
        {[1, 2, 3].map(i => (
          <div key={i} className="bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border p-5">
            <div className="h-5 bg-warm-border rounded w-1/3 mb-2" />
            <div className="h-4 bg-warm-border rounded w-2/3 mb-2" />
            <div className="h-3 bg-warm-border rounded w-1/4" />
          </div>
        ))}
      </div>
    </div>
  )
}
