'use client'

import { useState, useEffect } from 'react'
import { useLocale, useTranslations } from 'next-intl'
import { PhotoViewer, buildPhotoViewerCopy, type PhotoViewerItem } from '@/components/photo-viewer'
import { Button, EditIcon, PlusIcon, RefreshIcon, TrashIcon, XIcon } from '@/components/ui/button'
import { VelvetDatePicker } from '@/components/forms/velvet-date-picker'
import { Modal } from '@/components/ui/modal'

interface Milestone {
  id: string
  title: string
  description: string | null
  date: string
  locationName: string | null
  isAutoGenerated: boolean
  photoId: string | null
  photo: { thumbnailUrl: string | null } | null
}

export function buildDashboardTimelinePreviewItems(milestones: Milestone[]): PhotoViewerItem[] {
  return milestones.flatMap(milestone => {
    if (!milestone.photoId || !milestone.photo?.thumbnailUrl) {
      return []
    }

    return [{
      id: milestone.photoId,
      src: milestone.photo.thumbnailUrl,
      alt: milestone.title,
      title: milestone.title,
    }]
  })
}

type Translator = (key: string, values?: Record<string, string | number>) => string

type TimelineNarrativeSummary = {
  rangeStart: string
  rangeEnd: string
  locationLabel: string
  locationCount: number
  isMixedLocation: boolean
  itemCount: number
}

type TimelineNarrativeGroup = {
  id: string
  milestones: Milestone[]
  summary: TimelineNarrativeSummary
}

type TimelineReadingMeta = {
  narrativeText: string
  hasGeneratedNarrative: boolean
}

type TimelineReadingCopy = {
  withLocationAndPhoto: (location: string) => string
  withLocation: (location: string) => string
  withPhoto: string
  generic: string
}

type TimelineNarrativeCopy = {
  multiLocationMany: (locationCount: number) => string
  singleLocationMany: (location: string) => string
  multiLocationSingle: (locationCount: number) => string
  singleLocationSingle: (location: string) => string
  genericMany: (itemCount: number) => string
  genericSingle: string
  multiLocationDescription: (locationCount: number) => string
  manyDescription: (itemCount: number) => string
  singleDescription: string
}

type TimelineRecommendationCopy = {
  withLocationAndPhoto: string
  withLocation: (location: string) => string
  withPhoto: string
  generic: string
}

const NARRATIVE_GROUP_GAP_DAYS = 45
const SAME_LOCATION_NEARBY_DAYS = 14

function diffDays(currentDate: string, previousDate: string) {
  return Math.round(
    Math.abs(new Date(currentDate).getTime() - new Date(previousDate).getTime()) /
      (1000 * 60 * 60 * 24)
  )
}

export function buildTimelineNarrativeSummary(
  milestones: Array<Pick<Milestone, 'date' | 'locationName'>>
): TimelineNarrativeSummary {
  const rangeStart = milestones[0]?.date ?? ''
  const rangeEnd = milestones[milestones.length - 1]?.date ?? ''
  const locations = milestones
    .map(milestone => milestone.locationName?.trim())
    .filter((location): location is string => Boolean(location))
  const uniqueLocations = [...new Set(locations)]
  const locationCount = uniqueLocations.length
  const isMixedLocation = locationCount > 1

  return {
    rangeStart,
    rangeEnd,
    locationLabel: isMixedLocation ? '' : (uniqueLocations[0] ?? ''),
    locationCount,
    isMixedLocation,
    itemCount: milestones.length,
  }
}

export function buildTimelineNarrativeGroups(milestones: Milestone[]): TimelineNarrativeGroup[] {
  if (milestones.length === 0) return []

  const sortedMilestones = [...milestones].sort((left, right) => {
    const dateDiff = new Date(left.date).getTime() - new Date(right.date).getTime()
    if (dateDiff !== 0) return dateDiff

    return left.id.localeCompare(right.id)
  })
  const groups: TimelineNarrativeGroup[] = []

  for (const milestone of sortedMilestones) {
    const previousGroup = groups[groups.length - 1]
    const previousMilestone = previousGroup?.milestones[previousGroup.milestones.length - 1]

    if (!previousGroup || !previousMilestone) {
      groups.push({
        id: `group-${milestone.id}`,
        milestones: [milestone],
        summary: buildTimelineNarrativeSummary([milestone]),
      })
      continue
    }

    const gapDays = diffDays(milestone.date, previousMilestone.date)
    const normalizedLocation = milestone.locationName?.trim()
    const normalizedPreviousLocation = previousMilestone.locationName?.trim()
    const sameLocation = Boolean(normalizedLocation) && normalizedLocation === normalizedPreviousLocation

    if (sameLocation && gapDays <= SAME_LOCATION_NEARBY_DAYS) {
      previousGroup.milestones.push(milestone)
      previousGroup.summary = buildTimelineNarrativeSummary(previousGroup.milestones)
      continue
    }

    if (gapDays > NARRATIVE_GROUP_GAP_DAYS) {
      groups.push({
        id: `group-${milestone.id}`,
        milestones: [milestone],
        summary: buildTimelineNarrativeSummary([milestone]),
      })
      continue
    }

    previousGroup.milestones.push(milestone)
    previousGroup.summary = buildTimelineNarrativeSummary(previousGroup.milestones)
  }

  return groups
}

function formatTimelineNarrativeRange(
  summary: Pick<TimelineNarrativeSummary, 'rangeStart' | 'rangeEnd'>,
  locale: string
) {
  if (!summary.rangeStart) return ''

  const dateFormat: Intl.DateTimeFormatOptions = {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }
  const startLabel = new Date(summary.rangeStart).toLocaleDateString(locale, dateFormat)

  if (!summary.rangeEnd || summary.rangeEnd === summary.rangeStart) {
    return startLabel
  }

  const endLabel = new Date(summary.rangeEnd).toLocaleDateString(locale, dateFormat)
  return `${startLabel} - ${endLabel}`
}

export function buildTimelineNarrativeHeading(
  summary: TimelineNarrativeSummary,
  copy: TimelineNarrativeCopy
) {
  if (summary.isMixedLocation && summary.itemCount > 1) {
    return copy.multiLocationMany(summary.locationCount)
  }

  if (summary.locationLabel && summary.itemCount > 1) {
    return copy.singleLocationMany(summary.locationLabel)
  }

  if (summary.isMixedLocation) {
    return copy.multiLocationSingle(summary.locationCount)
  }

  if (summary.locationLabel) {
    return copy.singleLocationSingle(summary.locationLabel)
  }

  if (summary.itemCount > 1) {
    return copy.genericMany(summary.itemCount)
  }

  return copy.genericSingle
}

export function buildTimelineNarrativeDescription(
  summary: TimelineNarrativeSummary,
  copy: TimelineNarrativeCopy
) {
  if (summary.isMixedLocation && summary.itemCount > 1) {
    return copy.multiLocationDescription(summary.locationCount)
  }

  if (summary.itemCount > 1) {
    return copy.manyDescription(summary.itemCount)
  }

  return copy.singleDescription
}

export function buildTimelineReadingMeta(
  milestone: Pick<Milestone, 'description' | 'locationName' | 'photoId'>,
  copy: TimelineReadingCopy = {
    withLocationAndPhoto: location =>
      `这是一段和“${location}”有关、也已经关联到具体照片的回忆节点。`,
    withLocation: location => `这是一段和“${location}”有关的回忆节点。`,
    withPhoto: '这是从照片里提前提炼出来的一段回忆节点。',
    generic: '这是一个值得保留在时间线里的阶段节点。',
  }
): TimelineReadingMeta {
  const authoredDescription = milestone.description?.trim()
  const normalizedLocationName = milestone.locationName?.trim()

  if (authoredDescription) {
    return {
      narrativeText: authoredDescription,
      hasGeneratedNarrative: false,
    }
  }

  if (normalizedLocationName && milestone.photoId) {
    return {
      narrativeText: copy.withLocationAndPhoto(normalizedLocationName),
      hasGeneratedNarrative: true,
    }
  }

  if (normalizedLocationName) {
    return {
      narrativeText: copy.withLocation(normalizedLocationName),
      hasGeneratedNarrative: true,
    }
  }

  if (milestone.photoId) {
    return {
      narrativeText: copy.withPhoto,
      hasGeneratedNarrative: true,
    }
  }

  return {
    narrativeText: copy.generic,
    hasGeneratedNarrative: true,
  }
}

export function buildTimelineUiText(t: Translator) {
  return {
    title: t('title'),
    create: t('create'),
    empty: t('empty'),
    reviewGenerated: t('reviewGenerated'),
    confirmGenerated: t('confirmGenerated'),
    confirmAllGenerated: t('confirmAllGenerated'),
    ignoreGenerated: t('ignoreGenerated'),
    relatedPhoto: t('relatedPhoto'),
    narrativeFallbackLabel: t('narrativeFallbackLabel'),
    readingNarrativeWithLocationAndPhoto: (location: string) =>
      t('readingNarrativeWithLocationAndPhoto', { location }),
    readingNarrativeWithLocation: (location: string) =>
      t('readingNarrativeWithLocation', { location }),
    readingNarrativeWithPhoto: t('readingNarrativeWithPhoto'),
    readingNarrativeGeneric: t('readingNarrativeGeneric'),
    recommendationReason: t('recommendationReason'),
    recommendationReasonWithLocationAndPhoto: t('recommendationReasonWithLocationAndPhoto'),
    recommendationReasonWithLocation: (location: string) =>
      t('recommendationReasonWithLocation', { location }),
    recommendationReasonWithPhoto: t('recommendationReasonWithPhoto'),
    recommendationReasonGeneric: t('recommendationReasonGeneric'),
    mergeSuggestionTitle: t('mergeSuggestionTitle'),
    mergeSuggestionHint: (location: string, days: number) =>
      t('mergeSuggestionHint', { location, days }),
    mergeKeepPrimary: t('mergeKeepPrimary'),
    mergeRemoveDuplicate: t('mergeRemoveDuplicate'),
    pendingSection: t('pendingSection'),
    confirmedSection: t('confirmedSection'),
    pendingReview: (count: number) => t('pendingReview', { count }),
    narrativeGroupHeadingMultiLocationMany: (locationCount: number) =>
      t('narrativeGroupHeadingMultiLocationMany', { locationCount }),
    narrativeGroupHeadingSingleLocationMany: (location: string) =>
      t('narrativeGroupHeadingSingleLocationMany', { location }),
    narrativeGroupHeadingMultiLocationSingle: (locationCount: number) =>
      t('narrativeGroupHeadingMultiLocationSingle', { locationCount }),
    narrativeGroupHeadingSingleLocationSingle: (location: string) =>
      t('narrativeGroupHeadingSingleLocationSingle', { location }),
    narrativeGroupHeadingGenericMany: (itemCount: number) =>
      t('narrativeGroupHeadingGenericMany', { itemCount }),
    narrativeGroupHeadingGenericSingle: t('narrativeGroupHeadingGenericSingle'),
    narrativeGroupDescriptionMultiLocation: (locationCount: number) =>
      t('narrativeGroupDescriptionMultiLocation', { locationCount }),
    narrativeGroupDescriptionMany: (itemCount: number) =>
      t('narrativeGroupDescriptionMany', { itemCount }),
    narrativeGroupDescriptionSingle: t('narrativeGroupDescriptionSingle'),
  }
}

export function buildTimelineMilestoneMeta({
  isAutoGenerated,
}: {
  isAutoGenerated: boolean
}) {
  return {
    showAiBadge: isAutoGenerated,
    needsReview: isAutoGenerated,
  }
}

export function buildTimelineMilestoneActionState({
  isAutoGenerated,
}: {
  isAutoGenerated: boolean
}) {
  return {
    showConfirmAction: isAutoGenerated,
    showIgnoreAction: isAutoGenerated,
    showDeleteAction: !isAutoGenerated,
  }
}

export function buildTimelineReviewState(
  milestones: Array<{ isAutoGenerated: boolean }>
) {
  const pendingCount = milestones.filter(milestone => milestone.isAutoGenerated).length

  return {
    pendingCount,
    hasPending: pendingCount > 0,
  }
}

export function buildPendingGeneratedMilestoneIds(
  milestones: Array<{ id: string; isAutoGenerated: boolean }>
) {
  return milestones
    .filter(milestone => milestone.isAutoGenerated)
    .map(milestone => milestone.id)
}

export function buildTimelineSections<T extends { isAutoGenerated: boolean }>(milestones: T[]) {
  const pending = milestones.filter(milestone => milestone.isAutoGenerated)
  const confirmed = milestones.filter(milestone => !milestone.isAutoGenerated)

  return {
    pending,
    confirmed,
    hasPending: pending.length > 0,
  }
}

export function buildMilestoneRecommendationReason({
  isAutoGenerated,
  locationName,
  photoId,
  copy = {
    withLocationAndPhoto: '这条候选同时关联了地点和照片，适合作为一段回忆的清晰节点。',
    withLocation: (location: string) =>
      `这条候选记录了地点“${location}”，适合你判断它是不是一次值得保留的阶段节点。`,
    withPhoto: '这条候选已经关联到具体照片，适合快速判断这是不是一段应该进入时间线的回忆。',
    generic:
      '这条候选把一张可能重要的时刻提前提了出来，适合你快速确认是否值得留在时间线里。',
  },
}: {
  isAutoGenerated: boolean
  locationName: string | null
  photoId: string | null
  copy?: TimelineRecommendationCopy
}) {
  if (!isAutoGenerated) return ''
  if (locationName && photoId) {
    return copy.withLocationAndPhoto
  }
  if (locationName) {
    return copy.withLocation(locationName)
  }
  if (photoId) {
    return copy.withPhoto
  }

  return copy.generic
}

export function buildTimelineMergeSuggestions<T extends {
  id: string
  title: string
  date: string
  locationName: string | null
  isAutoGenerated: boolean
}>(milestones: T[]) {
  const confirmed = milestones.filter(milestone => !milestone.isAutoGenerated && milestone.locationName)
  const suggestions: Array<{
    primaryId: string
    primaryTitle: string
    duplicateId: string
    duplicateTitle: string
    locationName: string
    dateGapDays: number
  }> = []

  for (let i = 0; i < confirmed.length; i += 1) {
    const current = confirmed[i]!
    const currentDate = new Date(current.date)

    for (let j = i + 1; j < confirmed.length; j += 1) {
      const candidate = confirmed[j]!
      if (candidate.locationName !== current.locationName) continue

      const candidateDate = new Date(candidate.date)
      const dateGapDays = Math.round(
        Math.abs(candidateDate.getTime() - currentDate.getTime()) / (1000 * 60 * 60 * 24)
      )

      if (dateGapDays <= 3) {
        suggestions.push({
          primaryId: current.id,
          primaryTitle: current.title,
          duplicateId: candidate.id,
          duplicateTitle: candidate.title,
          locationName: current.locationName!,
          dateGapDays,
        })
        break
      }
    }
  }

  return suggestions
}

export default function TimelinePage() {
  const t = useTranslations('TimelinePage')
  const viewerT = useTranslations('PhotoViewer')
  const locale = useLocale()
  const [milestones, setMilestones] = useState<Milestone[]>([])
  const [coupleId, setCoupleId] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [showCreate, setShowCreate] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [pendingDeleteMilestoneId, setPendingDeleteMilestoneId] = useState<string | null>(null)
  const [deletingMilestoneId, setDeletingMilestoneId] = useState<string | null>(null)
  const [previewPhotoId, setPreviewPhotoId] = useState<string | null>(null)
  const [refreshKey, setRefreshKey] = useState(0)

  useEffect(() => {
    async function fetchData() {
      const coupleRes = await fetch('/api/couples/mine')
      if (!coupleRes.ok) return setLoading(false)
      const couple = await coupleRes.json()
      setCoupleId(couple.id)

      const res = await fetch(`/api/couples/${couple.id}/milestones`)
      if (res.ok) {
        const data = await res.json()
        setMilestones(data.milestones)
      }
      setLoading(false)
    }
    fetchData()
  }, [refreshKey])

  async function handleCreate(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    if (!coupleId) return
    const formData = new FormData(e.currentTarget)
    const date = String(formData.get('date') ?? '').trim()
    if (!date) return

    const res = await fetch(`/api/couples/${coupleId}/milestones`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: formData.get('title'),
        description: formData.get('description') || undefined,
        date,
        locationName: formData.get('locationName') || undefined,
      }),
    })

    if (res.ok) {
      setShowCreate(false)
      setRefreshKey(k => k + 1)
    }
  }

  async function handleUpdate(e: React.FormEvent<HTMLFormElement>, id: string) {
    e.preventDefault()
    if (!coupleId) return
    const formData = new FormData(e.currentTarget)
    const date = String(formData.get('date') ?? '').trim()
    if (!date) return

    await fetch(`/api/couples/${coupleId}/milestones/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: formData.get('title'),
        description: formData.get('description') || null,
        date,
        locationName: formData.get('locationName') || null,
      }),
    })
    setEditingId(null)
    setRefreshKey(k => k + 1)
  }

  async function handleDelete(id: string) {
    setPendingDeleteMilestoneId(id)
  }

  async function confirmDeleteMilestone() {
    if (!coupleId || !pendingDeleteMilestoneId) return
    setDeletingMilestoneId(pendingDeleteMilestoneId)
    await fetch(`/api/couples/${coupleId}/milestones/${pendingDeleteMilestoneId}`, { method: 'DELETE' })
    setDeletingMilestoneId(null)
    setPendingDeleteMilestoneId(null)
    setRefreshKey(k => k + 1)
  }

  async function handleConfirmGenerated(id: string) {
    if (!coupleId) return

    await fetch(`/api/couples/${coupleId}/milestones/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        isAutoGenerated: false,
      }),
    })

    setRefreshKey(k => k + 1)
  }

  async function handleConfirmAllGenerated() {
    if (!coupleId) return

    const pendingIds = buildPendingGeneratedMilestoneIds(milestones)
    if (pendingIds.length === 0) return

    await Promise.all(
      pendingIds.map(id =>
        fetch(`/api/couples/${coupleId}/milestones/${id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            isAutoGenerated: false,
          }),
        })
      )
    )

    setRefreshKey(k => k + 1)
  }

  if (loading) return <TimelineSkeleton />
  const uiText = buildTimelineUiText(t)
  const narrativeCopy = {
    multiLocationMany: uiText.narrativeGroupHeadingMultiLocationMany,
    singleLocationMany: uiText.narrativeGroupHeadingSingleLocationMany,
    multiLocationSingle: uiText.narrativeGroupHeadingMultiLocationSingle,
    singleLocationSingle: uiText.narrativeGroupHeadingSingleLocationSingle,
    genericMany: uiText.narrativeGroupHeadingGenericMany,
    genericSingle: uiText.narrativeGroupHeadingGenericSingle,
    multiLocationDescription: uiText.narrativeGroupDescriptionMultiLocation,
    manyDescription: uiText.narrativeGroupDescriptionMany,
    singleDescription: uiText.narrativeGroupDescriptionSingle,
  }
  const reviewState = buildTimelineReviewState(milestones)
  const sections = buildTimelineSections(milestones)
  const confirmedNarrativeGroups = buildTimelineNarrativeGroups(sections.confirmed)
  const mergeSuggestions = buildTimelineMergeSuggestions(milestones)
  const previewItems = buildDashboardTimelinePreviewItems(milestones)
  const previewIndex = previewItems.findIndex(item => item.id === previewPhotoId)
  const activePreviewIndex = previewIndex >= 0 ? previewIndex : 0
  const viewerCopy = buildPhotoViewerCopy(viewerT)

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold text-warm-text">{uiText.title}</h1>
          {reviewState.hasPending ? (
            <div className="flex flex-wrap items-center gap-3">
              <p className="text-sm text-info">{uiText.pendingReview(reviewState.pendingCount)}</p>
              <Button
                type="button"
                onClick={handleConfirmAllGenerated}
                size="xs"
                variant="subtle"
              >
                {uiText.confirmAllGenerated}
              </Button>
            </div>
          ) : null}
        </div>
        <Button
          onClick={() => setShowCreate(true)}
          variant="brand"
          leadingIcon={<PlusIcon />}
        >
          {uiText.create}
        </Button>
      </div>

      {mergeSuggestions.length > 0 ? (
        <section className="mb-6 rounded-[var(--radius-lg)] border border-warm-border bg-warm-surface p-4">
          <h2 className="text-sm font-semibold text-warm-text">{uiText.mergeSuggestionTitle}</h2>
          <div className="mt-3 space-y-3">
            {mergeSuggestions.map(suggestion => (
              <div
                key={`${suggestion.primaryId}:${suggestion.duplicateId}`}
                className="rounded-[var(--radius-md)] border border-warm-border bg-warm-bg px-3 py-3"
              >
                <p className="text-sm text-warm-muted">
                  {uiText.mergeSuggestionHint(suggestion.locationName, suggestion.dateGapDays)}
                </p>
                <div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-warm-text">
                  <span className="rounded-full bg-success/10 px-2.5 py-1 text-success">
                    {uiText.mergeKeepPrimary}: {suggestion.primaryTitle}
                  </span>
                  <span className="rounded-full bg-warm-surface px-2.5 py-1">
                    {uiText.mergeRemoveDuplicate}: {suggestion.duplicateTitle}
                  </span>
                </div>
                <div className="mt-3">
                  <Button
                    type="button"
                    onClick={() => void handleDelete(suggestion.duplicateId)}
                    size="sm"
                    variant="secondary"
                    leadingIcon={<TrashIcon />}
                  >
                    {uiText.mergeRemoveDuplicate}
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      {milestones.length === 0 ? (
        <div className="text-center py-20 bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border">
          <p className="text-warm-muted mb-4">{uiText.empty}</p>
          <Button
            onClick={() => setShowCreate(true)}
            variant="secondary"
            leadingIcon={<PlusIcon />}
          >
            {t('createFirst')}
          </Button>
        </div>
      ) : (
        <div className="relative">
          {/* 时间线竖线 */}
          <div className="absolute left-6 top-0 bottom-0 w-px bg-warm-border" />

          <div className="space-y-8">
            {sections.pending.length > 0 ? (
              <section className="space-y-4">
                <div className="pl-14">
                  <h2 className="text-sm font-semibold uppercase tracking-[0.18em] text-info">
                    {uiText.pendingSection}
                  </h2>
                </div>
                {sections.pending.map(m => (
                  <MilestoneCard
                    key={m.id}
                    milestone={m}
                    locale={locale}
                    editingId={editingId}
                    setEditingId={setEditingId}
                    handleUpdate={handleUpdate}
                    handleDelete={handleDelete}
                    handleConfirmGenerated={handleConfirmGenerated}
                    inputClass={inputClass}
                    t={t}
                    uiText={uiText}
                    onPreviewPhoto={photoId => setPreviewPhotoId(photoId)}
                  />
                ))}
              </section>
            ) : null}

            {sections.confirmed.length > 0 ? (
              <section className="space-y-4">
                <div className="pl-14">
                  <h2 className="text-sm font-semibold uppercase tracking-[0.18em] text-warm-muted">
                    {uiText.confirmedSection}
                  </h2>
                </div>
                {confirmedNarrativeGroups.map(group => (
                  <div
                    key={group.id}
                    className="rounded-[var(--radius-xl)] border border-warm-border/70 bg-warm-surface/50 py-4"
                  >
                    <div className="px-6 pb-4 pl-14">
                      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-warm-muted">
                        {formatTimelineNarrativeRange(group.summary, locale)}
                      </p>
                      <h3 className="mt-2 text-base font-semibold text-warm-text">
                        {buildTimelineNarrativeHeading(group.summary, narrativeCopy)}
                      </h3>
                      <p className="mt-1 text-sm text-warm-muted">
                        {buildTimelineNarrativeDescription(group.summary, narrativeCopy)}
                      </p>
                    </div>
                    <div className="space-y-4">
                      {group.milestones.map(m => (
                        <MilestoneCard
                          key={m.id}
                          milestone={m}
                          locale={locale}
                          editingId={editingId}
                          setEditingId={setEditingId}
                          handleUpdate={handleUpdate}
                          handleDelete={handleDelete}
                          handleConfirmGenerated={handleConfirmGenerated}
                          inputClass={inputClass}
                          t={t}
                          uiText={uiText}
                          onPreviewPhoto={photoId => setPreviewPhotoId(photoId)}
                        />
                      ))}
                    </div>
                  </div>
                ))}
              </section>
            ) : null}
          </div>
        </div>
      )}

      {/* 创建弹窗 */}
      <Modal
        open={showCreate}
        onClose={() => setShowCreate(false)}
        title={t('createTitle')}
        width="md"
        hideFooter
      >
        <form onSubmit={handleCreate} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldTitle')}</label>
            <input name="title" required autoFocus className={inputClass} placeholder={t('fieldTitlePlaceholder')} />
          </div>
          <div>
            <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldDate')}</label>
            <VelvetDatePicker
              ariaLabel={t('fieldDate')}
              locale={locale}
              name="date"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldLocation')}</label>
            <input name="locationName" className={inputClass} placeholder={t('fieldLocationPlaceholder')} />
          </div>
          <div>
            <label className="block text-sm font-medium text-warm-text mb-1.5">{t('fieldDescription')}</label>
            <textarea name="description" rows={2} className={inputClass + ' resize-none'} placeholder={t('fieldDescriptionPlaceholder')} />
          </div>
          <div className="flex gap-3 pt-2">
            <Button type="button" onClick={() => setShowCreate(false)} className="flex-1" fullWidth variant="secondary">
              {t('cancel')}
            </Button>
            <Button type="submit" className="flex-1" fullWidth variant="brand" leadingIcon={<PlusIcon />}>
              {t('submit')}
            </Button>
          </div>
        </form>
      </Modal>

      <Modal
        open={pendingDeleteMilestoneId !== null}
        onClose={() => setPendingDeleteMilestoneId(null)}
        title={t('deleteTitle')}
        description={t('deleteConfirm')}
        confirmText={t('deleteTitle')}
        cancelText={t('cancel')}
        confirmVariant="danger"
        confirmLoading={deletingMilestoneId !== null}
        onConfirm={confirmDeleteMilestone}
      >
        <p className="text-sm text-warm-muted">
          {milestones.find(milestone => milestone.id === pendingDeleteMilestoneId)?.title ?? ''}
        </p>
      </Modal>

      <PhotoViewer
        open={previewPhotoId !== null && previewItems.length > 0}
        items={previewItems}
        currentIndex={activePreviewIndex}
        onIndexChange={index => setPreviewPhotoId(previewItems[index]?.id ?? null)}
        onClose={() => setPreviewPhotoId(null)}
        copy={viewerCopy}
      />
    </div>
  )
}

const inputClass = `w-full px-4 py-2.5 rounded-[var(--radius-md)] border border-warm-border
  bg-warm-bg text-warm-text placeholder:text-warm-muted/60
  focus:ring-2 focus:ring-warm-accent/30 focus:border-warm-accent outline-none
  transition-all duration-200 text-sm`

function TimelineSkeleton() {
  return (
    <div className="animate-pulse">
      <div className="flex justify-between mb-6">
        <div className="h-8 bg-warm-border rounded w-24" />
        <div className="h-9 bg-warm-border rounded w-28" />
      </div>
      <div className="space-y-4 pl-14">
        {[1, 2, 3].map(i => (
          <div key={i} className="bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border p-5">
            <div className="h-5 bg-warm-border rounded w-1/3 mb-2" />
            <div className="h-4 bg-warm-border rounded w-2/3 mb-2" />
            <div className="h-3 bg-warm-border rounded w-1/4" />
          </div>
        ))}
      </div>
    </div>
  )
}

function MilestoneCard({
  milestone: m,
  locale,
  editingId,
  setEditingId,
  handleUpdate,
  handleDelete,
  handleConfirmGenerated,
  onPreviewPhoto,
  inputClass,
  t,
  uiText,
}: {
  milestone: Milestone
  locale: string
  editingId: string | null
  setEditingId: (id: string | null) => void
  handleUpdate: (e: React.FormEvent<HTMLFormElement>, id: string) => Promise<void>
  handleDelete: (id: string) => Promise<void>
  handleConfirmGenerated: (id: string) => Promise<void>
  onPreviewPhoto: (photoId: string) => void
  inputClass: string
  t: ReturnType<typeof useTranslations<'TimelinePage'>>
  uiText: ReturnType<typeof buildTimelineUiText>
}) {
  const meta = buildTimelineMilestoneMeta({ isAutoGenerated: m.isAutoGenerated })
  const actionState = buildTimelineMilestoneActionState({ isAutoGenerated: m.isAutoGenerated })
  const readingMeta = buildTimelineReadingMeta(m, {
    withLocationAndPhoto: uiText.readingNarrativeWithLocationAndPhoto,
    withLocation: uiText.readingNarrativeWithLocation,
    withPhoto: uiText.readingNarrativeWithPhoto,
    generic: uiText.readingNarrativeGeneric,
  })

  return (
    <div className="relative pl-14">
      <div className={`absolute left-[18px] top-5 h-5 w-5 rounded-full border-2 ${
        m.isAutoGenerated
          ? 'border-info bg-info/20'
          : 'border-warm-accent bg-warm-accent/20'
      }`}
      />

      <div className="bg-warm-surface rounded-[var(--radius-lg)] border border-warm-border p-5">
        {editingId === m.id ? (
          <form onSubmit={e => handleUpdate(e, m.id)} className="space-y-3">
            <input name="title" defaultValue={m.title} required className={inputClass} />
            <textarea name="description" defaultValue={m.description || ''} rows={2} className={inputClass + ' resize-none'} />
            <div className="flex gap-3">
              <div className="flex-1">
                <VelvetDatePicker
                  ariaLabel={t('fieldDate')}
                  defaultValue={m.date.split('T')[0]}
                  locale={locale}
                  name="date"
                />
              </div>
              <input name="locationName" defaultValue={m.locationName || ''} placeholder={t('locationPlaceholder')} className={inputClass + ' flex-1'} />
            </div>
            <div className="flex gap-2">
              <Button type="submit" size="xs" variant="brand" leadingIcon={<RefreshIcon />}>{t('save')}</Button>
              <Button type="button" size="xs" variant="secondary" onClick={() => setEditingId(null)} leadingIcon={<XIcon />}>{t('cancel')}</Button>
            </div>
          </form>
        ) : (
          <div className="flex items-start justify-between gap-3">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <h3 className="font-semibold text-warm-text">{m.title}</h3>
                {meta.showAiBadge ? (
                  <span className="px-1.5 py-0.5 text-[10px] text-info bg-info/10 rounded">
                    {t('aiGenerated')}
                  </span>
                ) : null}
              </div>
              <div className="mt-2 space-y-2">
                <p className="text-sm leading-6 text-warm-text/88">{readingMeta.narrativeText}</p>
              </div>
              {meta.needsReview ? (
                <p className="mt-2 text-sm text-info">
                  {uiText.recommendationReason}: {buildMilestoneRecommendationReason({
                    isAutoGenerated: m.isAutoGenerated,
                    locationName: m.locationName,
                    photoId: m.photoId,
                    copy: {
                      withLocationAndPhoto: uiText.recommendationReasonWithLocationAndPhoto,
                      withLocation: uiText.recommendationReasonWithLocation,
                      withPhoto: uiText.recommendationReasonWithPhoto,
                      generic: uiText.recommendationReasonGeneric,
                    },
                  })}
                </p>
              ) : null}
              <div className="flex flex-wrap gap-3 mt-3 text-xs text-warm-muted">
                <span>{new Date(m.date).toLocaleDateString(locale, {
                  year: 'numeric', month: 'long', day: 'numeric',
                })}
                </span>
                {m.locationName ? <span>{m.locationName}</span> : null}
                {m.photo ? <span>{uiText.relatedPhoto}</span> : null}
                {readingMeta.hasGeneratedNarrative ? (
                  <span className="inline-flex rounded-full bg-warm-bg px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.14em] text-warm-muted">
                    {uiText.narrativeFallbackLabel}
                  </span>
                ) : null}
              </div>
            </div>

            <div className="flex items-center gap-1 flex-shrink-0">
              {m.photo?.thumbnailUrl && m.photoId ? (
                <button
                  type="button"
                  onClick={() => onPreviewPhoto(m.photoId!)}
                  className="overflow-hidden rounded-[var(--radius-sm)] border border-warm-border/70 transition duration-200 hover:border-warm-accent/45"
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={m.photo.thumbnailUrl}
                    alt={m.title}
                    className="h-12 w-12 object-cover"
                  />
                </button>
              ) : null}
              {actionState.showConfirmAction ? (
                <Button
                  onClick={() => handleConfirmGenerated(m.id)}
                  size="xs"
                  variant="subtle"
                  title={uiText.confirmGenerated}
                >
                  {uiText.confirmGenerated}
                </Button>
              ) : null}
              {actionState.showIgnoreAction ? (
                <Button
                  onClick={() => handleDelete(m.id)}
                  size="xs"
                  variant="secondary"
                  title={uiText.ignoreGenerated}
                >
                  {uiText.ignoreGenerated}
                </Button>
              ) : null}
              <Button
                onClick={() => setEditingId(m.id)}
                size="xs"
                iconOnly
                variant="ghost"
                title={t('editTitle')}
                aria-label={t('editTitle')}
              >
                <EditIcon />
              </Button>
              {actionState.showDeleteAction ? (
                <Button
                  onClick={() => handleDelete(m.id)}
                  size="xs"
                  iconOnly
                  variant="ghost"
                  title={t('deleteTitle')}
                  aria-label={t('deleteTitle')}
                >
                  <TrashIcon />
                </Button>
              ) : null}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
