'use client'

import { motion } from 'framer-motion'
import { useLocale, useTranslations } from 'next-intl'
import { useMemo, useState } from 'react'
import { PhotoViewer, buildPhotoViewerCopy, type PhotoViewerItem } from './photo-viewer'

export interface TimelineMilestone {
  id: string
  title: string
  description: string | null
  date: string
  locationName: string | null
  isAutoGenerated: boolean
  photo: {
    id: string
    thumbnailUrl: string | null
    displayUrl: string | null
  } | null
}

export function buildTimelinePreviewItems(milestones: TimelineMilestone[]): PhotoViewerItem[] {
  return milestones.flatMap(milestone => {
    const src = milestone.photo?.displayUrl || milestone.photo?.thumbnailUrl

    if (!src || !milestone.photo?.id) {
      return []
    }

    return [{
      id: milestone.photo.id,
      src,
      alt: milestone.title,
      title: milestone.title,
    }]
  })
}

function formatDate(dateStr: string, locale: string) {
  return new Date(dateStr).toLocaleDateString(locale, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

export function TimelineView({ milestones }: { milestones: TimelineMilestone[] }) {
  const locale = useLocale()
  const t = useTranslations('PhotoViewer')
  const previewItems = useMemo(() => buildTimelinePreviewItems(milestones), [milestones])
  const [previewPhotoId, setPreviewPhotoId] = useState<string | null>(null)
  const viewerCopy = useMemo(() => buildPhotoViewerCopy(t), [t])
  const previewIndex = previewItems.findIndex(item => item.id === previewPhotoId)
  const activePreviewIndex = previewIndex >= 0 ? previewIndex : 0

  return (
    <>
      <div className="relative">
        <div
          className="absolute top-0 bottom-0 w-px bg-film-accent/20
            left-6 md:left-1/2 md:-translate-x-px"
        />

        <div className="space-y-10 md:space-y-14">
          {milestones.map((milestone, index) => {
            const isLeft = index % 2 === 0

            return (
              <motion.div
                key={milestone.id}
                className={`relative flex items-start
                  pl-14 md:pl-0
                  ${isLeft ? 'md:flex-row' : 'md:flex-row-reverse'}`}
                initial={{ opacity: 0, x: isLeft ? -40 : 40 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ duration: 0.5, delay: 0.1 }}
              >
                <TimelineDot isAuto={milestone.isAutoGenerated} />
                <div className="hidden md:block md:w-1/2" />

                <div className="w-full md:w-1/2 md:px-8">
                  <MilestoneCard
                    milestone={milestone}
                    locale={locale}
                    onPreviewPhoto={photoId => setPreviewPhotoId(photoId)}
                  />
                </div>
              </motion.div>
            )
          })}
        </div>
      </div>

      <PhotoViewer
        open={previewPhotoId !== null && previewItems.length > 0}
        items={previewItems}
        currentIndex={activePreviewIndex}
        onIndexChange={index => setPreviewPhotoId(previewItems[index]?.id ?? null)}
        onClose={() => setPreviewPhotoId(null)}
        copy={viewerCopy}
      />
    </>
  )
}

function TimelineDot({ isAuto }: { isAuto: boolean }) {
  return (
    <div
      className={`absolute top-2 z-10 h-4 w-4 rounded-full border-2
        left-[18px] md:left-1/2 md:-translate-x-1/2
        ${isAuto
          ? 'border-film-muted bg-film-muted/20'
          : 'border-film-accent-light bg-film-accent/30'
        }`}
    />
  )
}

function MilestoneCard({
  milestone,
  locale,
  onPreviewPhoto,
}: {
  milestone: TimelineMilestone
  locale: string
  onPreviewPhoto: (photoId: string) => void
}) {
  const photoUrl = milestone.photo?.displayUrl || milestone.photo?.thumbnailUrl

  return (
    <div
      className="rounded-[var(--radius-lg)] border border-film-accent/10 bg-film-surface p-5
        transition-colors duration-300 hover:border-film-accent/25"
    >
      <span
        className="mb-2 inline-block text-xs tracking-wider text-film-accent-light"
        style={{ fontFamily: 'var(--font-latin)' }}
      >
        {formatDate(milestone.date, locale)}
      </span>

      <div className="flex items-start gap-4">
        <div className="min-w-0 flex-1">
          <div className="mb-1 flex items-center gap-2">
            <h3
              className="text-base font-semibold text-film-text"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              {milestone.title}
            </h3>
            {milestone.isAutoGenerated ? (
              <span className="rounded border border-film-muted/20 bg-film-muted/10 px-1.5 py-0.5 text-[10px] text-film-muted">
                AI
              </span>
            ) : null}
          </div>

          {milestone.description ? (
            <p className="mt-1 text-sm leading-relaxed text-film-muted">
              {milestone.description}
            </p>
          ) : null}

          {milestone.locationName ? (
            <p className="mt-2 flex items-center gap-1 text-xs text-film-muted/70">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
                <circle cx="12" cy="10" r="3" />
              </svg>
              {milestone.locationName}
            </p>
          ) : null}
        </div>

        {photoUrl && milestone.photo?.id ? (
          <button
            type="button"
            onClick={() => onPreviewPhoto(milestone.photo!.id)}
            className="flex-shrink-0 overflow-hidden rounded-[var(--radius-sm)] border border-film-accent/14 transition duration-300 hover:-translate-y-0.5 hover:border-film-accent/35"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={photoUrl}
              alt={milestone.title}
              className="h-16 w-16 object-cover"
            />
          </button>
        ) : null}
      </div>
    </div>
  )
}
