'use client'

import { motion } from 'framer-motion'
import { useLocale } from 'next-intl'

export interface TimelineMilestone {
  id: string
  title: string
  description: string | null
  date: string
  locationName: string | null
  isAutoGenerated: boolean
  photo: {
    id: string
    thumbnailUrl: string | null
    displayUrl: string | null
  } | null
}

function formatDate(dateStr: string, locale: string) {
  return new Date(dateStr).toLocaleDateString(locale, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

export function TimelineView({ milestones }: { milestones: TimelineMilestone[] }) {
  const locale = useLocale()
  return (
    <div className="relative">
      {/* 中心线 (desktop) / 左侧线 (mobile) */}
      <div
        className="absolute top-0 bottom-0 w-px bg-film-accent/20
          left-6 md:left-1/2 md:-translate-x-px"
      />

      <div className="space-y-10 md:space-y-14">
        {milestones.map((m, i) => {
          const isLeft = i % 2 === 0

          return (
            <motion.div
              key={m.id}
              className={`relative flex items-start
                pl-14 md:pl-0
                ${isLeft ? 'md:flex-row' : 'md:flex-row-reverse'}`}
              initial={{ opacity: 0, x: isLeft ? -40 : 40 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.5, delay: 0.1 }}
            >
              {/* 时间点 */}
              <TimelineDot isAuto={m.isAutoGenerated} />

              {/* 间距占位 (desktop) */}
              <div className="hidden md:block md:w-1/2" />

                {/* 卡片 */}
              <div className="md:w-1/2 md:px-8 w-full">
                <MilestoneCard milestone={m} locale={locale} />
              </div>
            </motion.div>
          )
        })}
      </div>
    </div>
  )
}

function TimelineDot({ isAuto }: { isAuto: boolean }) {
  return (
    <div
      className={`absolute z-10 w-4 h-4 rounded-full border-2 top-2
        left-[18px] md:left-1/2 md:-translate-x-1/2
        ${isAuto
          ? 'border-film-muted bg-film-muted/20'
          : 'border-film-accent-light bg-film-accent/30'
        }`}
    />
  )
}

function MilestoneCard({ milestone: m, locale }: { milestone: TimelineMilestone; locale: string }) {
  const photoUrl = m.photo?.displayUrl || m.photo?.thumbnailUrl

  return (
    <div
      className="bg-film-surface rounded-[var(--radius-lg)] p-5 border border-film-accent/10
        hover:border-film-accent/25 transition-colors duration-300"
    >
      {/* 日期徽标 */}
      <span
        className="inline-block text-xs text-film-accent-light tracking-wider mb-2"
        style={{ fontFamily: 'var(--font-latin)' }}
      >
        {formatDate(m.date, locale)}
      </span>

      <div className="flex items-start gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <h3
              className="font-semibold text-film-text text-base"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              {m.title}
            </h3>
            {m.isAutoGenerated && (
              <span className="px-1.5 py-0.5 text-[10px] text-film-muted bg-film-muted/10 rounded border border-film-muted/20">
                AI
              </span>
            )}
          </div>

          {m.description && (
            <p className="text-sm text-film-muted leading-relaxed mt-1">
              {m.description}
            </p>
          )}

          {m.locationName && (
            <p className="text-xs text-film-muted/70 mt-2 flex items-center gap-1">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
                <circle cx="12" cy="10" r="3" />
              </svg>
              {m.locationName}
            </p>
          )}
        </div>

        {photoUrl && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={photoUrl}
            alt=""
            className="w-16 h-16 rounded-[var(--radius-sm)] object-cover flex-shrink-0"
          />
        )}
      </div>
    </div>
  )
}
