import { executePipeline } from './engine'
import { photoAnalyzer } from './photo-analyzer'
import { captionWriter } from './caption-writer'
import { layoutAdvisor } from './layout-advisor'
import { timelineBuilder } from './timeline-builder'
import { prisma } from '@/lib/prisma'
import type { DAGNode, PipelineInput, NodeResult } from './engine/types'

const dagNodes: DAGNode[] = [
  { id: 'photoAnalyzer', agent: photoAnalyzer, dependencies: [] },
  { id: 'captionWriter', agent: captionWriter, dependencies: ['photoAnalyzer'] },
  { id: 'layoutAdvisor', agent: layoutAdvisor, dependencies: ['photoAnalyzer'] },
  { id: 'timelineBuilder', agent: timelineBuilder, dependencies: ['photoAnalyzer'] },
]

export type PipelineExecutionStatus = 'COMPLETED' | 'FAILED' | 'DEGRADED'

type PipelineExecutionResultLike = {
  status: 'COMPLETED' | 'FAILED'
  nodeResults: Record<string, NodeResult>
  totalTokens: number
  totalCost: number
  duration: number
}

function getFirstFailedNode(nodeResults: Record<string, NodeResult>) {
  return Object.values(nodeResults).find(node => node.status === 'FAILED')
}

export function buildPipelineRunUpdate({
  result,
  triggerType = 'UPLOAD',
  attemptNumber = 1,
}: {
  result: PipelineExecutionResultLike
  triggerType?: string
  attemptNumber?: number
}) {
  const failedNode = getFirstFailedNode(result.nodeResults)
  const hasCompletedNode = Object.values(result.nodeResults).some(node => node.status === 'COMPLETED')
  const status: PipelineExecutionStatus =
    result.status === 'COMPLETED'
      ? 'COMPLETED'
      : failedNode && hasCompletedNode
        ? 'DEGRADED'
        : 'FAILED'

  return {
    status,
    triggerType,
    attemptNumber,
    nodeResults: JSON.parse(JSON.stringify(result.nodeResults)),
    totalTokens: result.totalTokens,
    totalCost: result.totalCost,
    completedAt: new Date(),
    duration: result.duration,
    errorCode: failedNode ? `${failedNode.nodeId.toUpperCase()}_FAILED` : null,
    summary: failedNode ? `${failedNode.nodeId} failed: ${failedNode.error ?? 'Unknown error'}` : null,
  }
}

export async function runAIPipeline(
  input: PipelineInput,
  coupleId: string,
  options?: { triggerType?: string }
) {
  const latestRun = await prisma.pipelineRun.findFirst({
    where: { photoId: input.photoId },
    orderBy: [{ attemptNumber: 'desc' }, { startedAt: 'desc' }],
    select: { attemptNumber: true },
  })
  const attemptNumber = (latestRun?.attemptNumber ?? 0) + 1
  const triggerType = options?.triggerType ?? 'UPLOAD'

  const run = await prisma.pipelineRun.create({
    data: {
      coupleId,
      photoId: input.photoId,
      triggerType,
      attemptNumber,
      dag: dagNodes.map(n => ({ id: n.id, dependencies: n.dependencies })),
    },
  })

  const result = await executePipeline(dagNodes, input)
  const update = buildPipelineRunUpdate({
    result,
    triggerType,
    attemptNumber,
  })

  await prisma.pipelineRun.update({
    where: { id: run.id },
    data: update,
  })

  return {
    ...result,
    status: update.status,
    errorCode: update.errorCode,
    summary: update.summary,
    triggerType,
    attemptNumber,
  }
}

export async function applyPipelineResults(
  photoId: string,
  nodeResults: Record<string, NodeResult>,
  coupleId: string
) {
  const caption = nodeResults.captionWriter?.output as { caption?: string; keywords?: string[] } | undefined
  const layout = nodeResults.layoutAdvisor?.output as { layout?: string } | undefined
  const analysis = nodeResults.photoAnalyzer?.output as {
    scene?: string; mood?: string; composition?: string; colorTone?: string
  } | undefined
  const timeline = nodeResults.timelineBuilder?.output as {
    shouldCreateMilestone?: boolean
    milestone?: { title: string; description: string; date: string; locationName: string }
  } | undefined

  await prisma.photo.update({
    where: { id: photoId },
    data: {
      aiCaption: caption?.caption,
      aiKeywords: caption?.keywords || [],
      aiLayout: layout?.layout || 'side-by-side',
      aiScene: analysis?.scene,
      aiMood: analysis?.mood,
      aiComposition: analysis?.composition,
      aiColorTone: analysis?.colorTone,
    },
  })

  if (timeline?.shouldCreateMilestone && timeline.milestone) {
    await prisma.milestone.create({
      data: {
        coupleId,
        title: timeline.milestone.title,
        description: timeline.milestone.description,
        date: new Date(timeline.milestone.date),
        locationName: timeline.milestone.locationName,
        photoId,
        isAutoGenerated: true,
      },
    })
  }
}
