import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { withAuth, type AuthContext } from '@/lib/api-middleware'

type MilestoneRouteDeps = {
  prismaClient?: {
    milestone: {
      updateMany: (args: Record<string, unknown>) => Promise<{ count: number }>
      findUnique: (args: Record<string, unknown>) => Promise<unknown>
      deleteMany: (args: Record<string, unknown>) => Promise<unknown>
    }
  }
}

type MilestonePatchBody = {
  title?: unknown
  description?: unknown
  date?: unknown
  locationName?: unknown
  isAutoGenerated?: unknown
}

function normalizeOptionalString(value: unknown) {
  if (typeof value !== 'string') {
    return undefined
  }

  const trimmed = value.trim()
  return trimmed.length > 0 ? trimmed : null
}

export function buildMilestoneUpdateData(body: MilestonePatchBody) {
  const data: Record<string, unknown> = {}

  const title = normalizeOptionalString(body.title)
  if (title) {
    data.title = title
  }

  if (body.description !== undefined) {
    const description = normalizeOptionalString(body.description)
    if (description !== undefined) {
      data.description = description
    }
  }

  if (typeof body.date === 'string' && body.date.trim()) {
    data.date = new Date(body.date)
  }

  if (body.locationName !== undefined) {
    const locationName = normalizeOptionalString(body.locationName)
    if (locationName !== undefined) {
      data.locationName = locationName
    }
  }

  if (typeof body.isAutoGenerated === 'boolean') {
    data.isAutoGenerated = body.isAutoGenerated
  }

  return data
}

async function loadPrismaClient() {
  return prisma as unknown as NonNullable<MilestoneRouteDeps['prismaClient']>
}

export function createPatchMilestoneHandler(deps: MilestoneRouteDeps = {}) {
  return async (req: Request, { coupleUser }: AuthContext, params: Record<string, string>) => {
    const prismaClient = deps.prismaClient ?? await loadPrismaClient()
    const body = await req.json() as MilestonePatchBody
    const ms = await prismaClient.milestone.updateMany({
      where: { id: params.milestoneId, coupleId: coupleUser.coupleId },
      data: buildMilestoneUpdateData(body),
    })
    if (ms.count === 0) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
    }
    const updated = await prismaClient.milestone.findUnique({ where: { id: params.milestoneId } })
    return NextResponse.json(updated)
  }
}

export const PATCH = withAuth(createPatchMilestoneHandler())

export const DELETE = withAuth(async (req, { coupleUser }, params) => {
  await prisma.milestone.deleteMany({
    where: { id: params.milestoneId, coupleId: coupleUser.coupleId },
  })
  return new Response(null, { status: 204 })
})
