import assert from 'node:assert/strict'
import test from 'node:test'

import {
  buildTimelineMilestoneActionState,
  buildTimelineNarrativeDescription,
  buildTimelineNarrativeHeading,
  buildTimelineNarrativeGroups,
  buildTimelineNarrativeSummary,
  buildTimelineReadingMeta,
} from '../../src/app/(dashboard)/timeline/page'

const confirmedMilestones = [
  {
    id: 'm1',
    title: '广州见面',
    description: null,
    date: '2024-03-01T00:00:00.000Z',
    locationName: '广州',
    isAutoGenerated: false,
    photoId: 'p1',
    photo: { thumbnailUrl: '/1.jpg' },
  },
  {
    id: 'm2',
    title: '珠江夜晚',
    description: '一起散步到很晚。',
    date: '2024-03-10T00:00:00.000Z',
    locationName: '广州',
    isAutoGenerated: false,
    photoId: 'p2',
    photo: { thumbnailUrl: '/2.jpg' },
  },
  {
    id: 'm3',
    title: '杭州重逢',
    description: null,
    date: '2024-06-20T00:00:00.000Z',
    locationName: '杭州',
    isAutoGenerated: false,
    photoId: null,
    photo: null,
  },
] as const

const sameLocationNearbyMilestones = [
  {
    id: 'nearby-1',
    title: '广州周末',
    description: null,
    date: '2024-03-01T00:00:00.000Z',
    locationName: '广州',
    isAutoGenerated: false,
    photoId: null,
    photo: null,
  },
  {
    id: 'nearby-2',
    title: '广州再见',
    description: null,
    date: '2024-03-15T00:00:00.000Z',
    locationName: '广州',
    isAutoGenerated: false,
    photoId: null,
    photo: null,
  },
] as const

const sameLocationNearbyTrimmedMilestones = [
  {
    id: 'trimmed-1',
    title: '广州出发',
    description: null,
    date: '2024-03-01T00:00:00.000Z',
    locationName: '广州',
    isAutoGenerated: false,
    photoId: null,
    photo: null,
  },
  {
    id: 'trimmed-2',
    title: '广州到达',
    description: null,
    date: '2024-03-10T00:00:00.000Z',
    locationName: ' 广州 ',
    isAutoGenerated: false,
    photoId: null,
    photo: null,
  },
] as const

const mixedLocationMilestones = [
  {
    id: 'mixed-1',
    title: '广州见面',
    description: null,
    date: '2024-03-01T00:00:00.000Z',
    locationName: '广州',
    isAutoGenerated: false,
    photoId: null,
    photo: null,
  },
  {
    id: 'mixed-2',
    title: '杭州重逢',
    description: null,
    date: '2024-03-20T00:00:00.000Z',
    locationName: '杭州',
    isAutoGenerated: false,
    photoId: null,
    photo: null,
  },
] as const

const unsortedMilestones = [
  confirmedMilestones[2],
  confirmedMilestones[0],
  confirmedMilestones[1],
] as const

test('buildTimelineNarrativeGroups starts a new group after a large date gap', () => {
  const groups = buildTimelineNarrativeGroups([...confirmedMilestones])

  assert.equal(groups.length, 2)
  assert.deepEqual(groups.map(group => group.milestones.map(milestone => milestone.id)), [
    ['m1', 'm2'],
    ['m3'],
  ])
})

test('buildTimelineNarrativeGroups keeps same-location milestones together when they are within 14 days', () => {
  const groups = buildTimelineNarrativeGroups([...sameLocationNearbyMilestones])

  assert.equal(groups.length, 1)
  assert.equal(groups[0]?.summary.locationLabel, '广州')
  assert.deepEqual(groups[0]?.milestones.map(milestone => milestone.id), ['nearby-1', 'nearby-2'])
})

test('buildTimelineNarrativeGroups normalizes location names before applying same-location nearby rule', () => {
  const groups = buildTimelineNarrativeGroups([...sameLocationNearbyTrimmedMilestones])

  assert.equal(groups.length, 1)
  assert.equal(groups[0]?.summary.locationLabel, '广州')
  assert.equal(groups[0]?.summary.itemCount, 2)
})

test('buildTimelineNarrativeGroups sorts out-of-order milestones before grouping and summarizing', () => {
  const groups = buildTimelineNarrativeGroups([...unsortedMilestones])

  assert.equal(groups.length, 2)
  assert.deepEqual(groups.map(group => group.milestones.map(milestone => milestone.id)), [
    ['m1', 'm2'],
    ['m3'],
  ])
  assert.deepEqual(
    groups.map(group => [group.summary.rangeStart, group.summary.rangeEnd]),
    [
      ['2024-03-01T00:00:00.000Z', '2024-03-10T00:00:00.000Z'],
      ['2024-06-20T00:00:00.000Z', '2024-06-20T00:00:00.000Z'],
    ]
  )
})

test('buildTimelineNarrativeSummary provides locationLabel', () => {
  const summary = buildTimelineNarrativeSummary([...confirmedMilestones.slice(0, 2)])

  assert.equal(summary.locationLabel, '广州')
  assert.equal(summary.itemCount, 2)
  assert.equal(summary.locationCount, 1)
  assert.equal(summary.isMixedLocation, false)
})

test('buildTimelineNarrativeGroups provides stable summary metadata for multi-milestone groups', () => {
  const groups = buildTimelineNarrativeGroups([...confirmedMilestones])
  const firstGroupSummary = groups[0]?.summary

  assert.deepEqual(firstGroupSummary, {
    rangeStart: '2024-03-01T00:00:00.000Z',
    rangeEnd: '2024-03-10T00:00:00.000Z',
    locationLabel: '广州',
    itemCount: 2,
    locationCount: 1,
    isMixedLocation: false,
  })
})

test('buildTimelineNarrativeSummary marks mixed-location groups without defaulting to the first location', () => {
  const summary = buildTimelineNarrativeSummary([...mixedLocationMilestones])

  assert.equal(summary.locationLabel, '')
  assert.equal(summary.locationCount, 2)
  assert.equal(summary.isMixedLocation, true)
})

test('buildTimelineNarrativeHeading and description accept localized copy for confirmed groups', () => {
  const summary = buildTimelineNarrativeSummary([...mixedLocationMilestones])
  const copy = {
    multiLocationMany: (locationCount: number) => `Memory across ${locationCount} places`,
    singleLocationMany: (location: string) => `Moments from ${location}`,
    multiLocationSingle: (locationCount: number) => `A stop across ${locationCount} places`,
    singleLocationSingle: (location: string) => `A stop in ${location}`,
    genericMany: (itemCount: number) => `${itemCount} milestones in this chapter`,
    genericSingle: 'One confirmed milestone',
    multiLocationDescription: (locationCount: number) =>
      `These confirmed milestones span ${locationCount} places in time order.`,
    manyDescription: (itemCount: number) =>
      `These ${itemCount} confirmed milestones are grouped in time order.`,
    singleDescription: 'Only one confirmed milestone is in this group.',
  }

  assert.equal(buildTimelineNarrativeHeading(summary, copy), 'Memory across 2 places')
  assert.equal(
    buildTimelineNarrativeDescription(summary, copy),
    'These confirmed milestones span 2 places in time order.'
  )
})

test('buildTimelineMilestoneActionState hides confirm action for confirmed milestones', () => {
  assert.deepEqual(buildTimelineMilestoneActionState({ isAutoGenerated: true }), {
    showConfirmAction: true,
    showIgnoreAction: true,
    showDeleteAction: false,
  })
  assert.deepEqual(buildTimelineMilestoneActionState({ isAutoGenerated: false }), {
    showConfirmAction: false,
    showIgnoreAction: false,
    showDeleteAction: true,
  })
})

test('buildTimelineReadingMeta keeps authored descriptions when present', () => {
  const meta = buildTimelineReadingMeta(confirmedMilestones[1])

  assert.equal(meta.hasGeneratedNarrative, false)
  assert.equal(meta.narrativeText, '一起散步到很晚。')
})

test('buildTimelineReadingMeta generates location-aware fallback copy when location and photo exist', () => {
  const meta = buildTimelineReadingMeta(confirmedMilestones[0])

  assert.equal(meta.hasGeneratedNarrative, true)
  assert.equal(meta.narrativeText, '这是一段和“广州”有关、也已经关联到具体照片的回忆节点。')
})

test('buildTimelineReadingMeta falls back to a photo-only narrative when location is blank after trimming', () => {
  const meta = buildTimelineReadingMeta({
    description: null,
    locationName: '   ',
    photoId: 'p-blank-location',
  })

  assert.equal(meta.hasGeneratedNarrative, true)
  assert.equal(meta.narrativeText, '这是从照片里提前提炼出来的一段回忆节点。')
})

test('buildTimelineReadingMeta falls back to a generic milestone note when data is sparse', () => {
  const meta = buildTimelineReadingMeta({
    description: null,
    locationName: null,
    photoId: null,
  })

  assert.equal(meta.hasGeneratedNarrative, true)
  assert.match(meta.narrativeText, /值得保留/)
})
