import assert from 'node:assert/strict'
import test from 'node:test'

import {
  buildAlbumsUiText,
  buildAlbumFallbackCover,
  buildAlbumCardVisual,
} from '../../../src/app/(dashboard)/albums/page'
import {
  buildPendingGeneratedMilestoneIds,
  buildTimelineReviewState,
  buildTimelineUiText,
  buildTimelineMilestoneMeta,
} from '../../../src/app/(dashboard)/timeline/page'

test('buildAlbumsUiText returns translated primary copy', () => {
  const t = (key: string) =>
    ({
      title: 'Albums',
      create: 'New album',
      empty: 'No albums yet. Create one to get started.',
    })[key] ?? key

  assert.deepEqual(buildAlbumsUiText(t), {
    title: 'Albums',
    create: 'New album',
    empty: 'No albums yet. Create one to get started.',
  })
})

test('buildAlbumFallbackCover returns a stable recipe for the same album seed', () => {
  const first = buildAlbumFallbackCover({ id: 'album_1', title: '2024 夏天' })
  const second = buildAlbumFallbackCover({ id: 'album_1', title: '2024 夏天' })

  assert.deepEqual(second, first)
})

test('buildAlbumFallbackCover can vary recipes for same-title albums with different ids', () => {
  const first = buildAlbumFallbackCover({ id: 'album_1', title: '2024 夏天' })
  const second = buildAlbumFallbackCover({ id: 'album_2', title: '2024 夏天' })

  assert.notEqual(`${first.recipeKey}:${first.accentKey}`, `${second.recipeKey}:${second.accentKey}`)
})

test('buildAlbumCardVisual returns a generated fallback cover when no coverPhotoUrl exists', () => {
  const visual = buildAlbumCardVisual({
    id: 'album_1',
    title: '2024 夏天',
    coverPhotoUrl: null,
  })

  assert.equal(visual.kind, 'fallback')
  assert.equal(typeof visual.coverClassName, 'string')
  assert.equal(visual.coverClassName.includes('linear-gradient'), true)
})

test('buildAlbumCardVisual preserves the image path when coverPhotoUrl exists', () => {
  const visual = buildAlbumCardVisual({
    id: 'album_1',
    title: '2024 夏天',
    coverPhotoUrl: 'https://example.com/cover.jpg',
  })

  assert.deepEqual(visual, {
    kind: 'image',
    url: 'https://example.com/cover.jpg',
  })
})

test('buildTimelineUiText returns translated primary copy', () => {
  const t = (key: string, values?: Record<string, string | number>) =>
    ({
      title: 'Timeline',
      create: 'Add milestone',
      empty: 'No milestones yet',
      reviewGenerated: 'Review AI suggestions',
      confirmGenerated: 'Confirm',
      confirmAllGenerated: 'Confirm all',
      pendingReview: values?.count ? `${values.count} AI suggestions need review` : 'pendingReview',
    })[key] ?? key

  const uiText = buildTimelineUiText(t)
  assert.equal(uiText.title, 'Timeline')
  assert.equal(uiText.create, 'Add milestone')
  assert.equal(uiText.empty, 'No milestones yet')
  assert.equal(uiText.reviewGenerated, 'Review AI suggestions')
  assert.equal(uiText.confirmGenerated, 'Confirm')
  assert.equal(uiText.confirmAllGenerated, 'Confirm all')
  assert.equal(uiText.pendingReview(2), '2 AI suggestions need review')
})

test('buildTimelineMilestoneMeta marks AI milestones as pending review', () => {
  assert.deepEqual(
    buildTimelineMilestoneMeta({ isAutoGenerated: true }),
    {
      showAiBadge: true,
      needsReview: true,
    }
  )
})

test('buildTimelineMilestoneMeta treats manual milestones as already confirmed', () => {
  assert.deepEqual(
    buildTimelineMilestoneMeta({ isAutoGenerated: false }),
    {
      showAiBadge: false,
      needsReview: false,
    }
  )
})

test('buildTimelineReviewState counts pending AI milestones', () => {
  assert.deepEqual(
    buildTimelineReviewState([
      { isAutoGenerated: true },
      { isAutoGenerated: false },
      { isAutoGenerated: true },
    ]),
    {
      pendingCount: 2,
      hasPending: true,
    }
  )
})

test('buildPendingGeneratedMilestoneIds returns only AI-generated milestone ids', () => {
  assert.deepEqual(
    buildPendingGeneratedMilestoneIds([
      { id: 'ms_1', isAutoGenerated: true },
      { id: 'ms_2', isAutoGenerated: false },
      { id: 'ms_3', isAutoGenerated: true },
    ]),
    ['ms_1', 'ms_3']
  )
})
