import assert from 'node:assert/strict'
import test from 'node:test'

import {
  buildAlbumsUiText,
} from '../../../src/app/(dashboard)/albums/page'
import {
  buildTimelineReviewState,
  buildTimelineUiText,
  buildTimelineMilestoneMeta,
} from '../../../src/app/(dashboard)/timeline/page'

test('buildAlbumsUiText returns translated primary copy', () => {
  const t = (key: string) =>
    ({
      title: 'Albums',
      create: 'New album',
      empty: 'No albums yet. Create one to get started.',
    })[key] ?? key

  assert.deepEqual(buildAlbumsUiText(t), {
    title: 'Albums',
    create: 'New album',
    empty: 'No albums yet. Create one to get started.',
  })
})

test('buildTimelineUiText returns translated primary copy', () => {
  const t = (key: string, values?: Record<string, string | number>) =>
    ({
      title: 'Timeline',
      create: 'Add milestone',
      empty: 'No milestones yet',
      reviewGenerated: 'Review AI suggestions',
      confirmGenerated: 'Confirm',
      pendingReview: values?.count ? `${values.count} AI suggestions need review` : 'pendingReview',
    })[key] ?? key

  const uiText = buildTimelineUiText(t)
  assert.equal(uiText.title, 'Timeline')
  assert.equal(uiText.create, 'Add milestone')
  assert.equal(uiText.empty, 'No milestones yet')
  assert.equal(uiText.reviewGenerated, 'Review AI suggestions')
  assert.equal(uiText.confirmGenerated, 'Confirm')
  assert.equal(uiText.pendingReview(2), '2 AI suggestions need review')
})

test('buildTimelineMilestoneMeta marks AI milestones as pending review', () => {
  assert.deepEqual(
    buildTimelineMilestoneMeta({ isAutoGenerated: true }),
    {
      showAiBadge: true,
      needsReview: true,
    }
  )
})

test('buildTimelineMilestoneMeta treats manual milestones as already confirmed', () => {
  assert.deepEqual(
    buildTimelineMilestoneMeta({ isAutoGenerated: false }),
    {
      showAiBadge: false,
      needsReview: false,
    }
  )
})

test('buildTimelineReviewState counts pending AI milestones', () => {
  assert.deepEqual(
    buildTimelineReviewState([
      { isAutoGenerated: true },
      { isAutoGenerated: false },
      { isAutoGenerated: true },
    ]),
    {
      pendingCount: 2,
      hasPending: true,
    }
  )
})
