import assert from 'node:assert/strict'
import test from 'node:test'

import {
  buildDashboardTimelinePreviewItems,
  buildMilestoneRecommendationReason,
  buildTimelineMergeSuggestions,
  buildTimelineSections,
  buildTimelineUiText,
} from '../../../src/app/(dashboard)/timeline/page'
import { buildTimelinePreviewItems } from '../../../src/components/timeline-view'

test('buildTimelineUiText exposes candidate review copy', () => {
  const uiText = buildTimelineUiText((key, values) => {
    if (key === 'mergeSuggestionHint') {
      if (!values || !('location' in values) || !('days' in values)) {
        throw new Error('missing merge suggestion interpolation values')
      }

      return `${String(values.location)}:${String(values.days)}`
    }

    if (values && 'count' in values) {
      return `${key}:${String(values.count)}`
    }

    return key
  })

  assert.equal(uiText.reviewGenerated, 'reviewGenerated')
  assert.equal(uiText.confirmGenerated, 'confirmGenerated')
  assert.equal(uiText.ignoreGenerated, 'ignoreGenerated')
  assert.equal(uiText.relatedPhoto, 'relatedPhoto')
  assert.equal(uiText.recommendationReason, 'recommendationReason')
  assert.equal(uiText.mergeSuggestionTitle, 'mergeSuggestionTitle')
  assert.equal(uiText.mergeSuggestionHint('厦门', 2), '厦门:2')
  assert.equal(uiText.mergeKeepPrimary, 'mergeKeepPrimary')
  assert.equal(uiText.mergeRemoveDuplicate, 'mergeRemoveDuplicate')
  assert.equal(uiText.pendingReview(2), 'pendingReview:2')
})

test('buildTimelineSections splits pending generated milestones from confirmed milestones', () => {
  const sections = buildTimelineSections([
    {
      id: 'm1',
      isAutoGenerated: true,
      title: '候选里程碑',
      description: null,
      date: '2026-05-20T00:00:00.000Z',
      locationName: null,
      photoId: 'p1',
      photo: null,
    },
    {
      id: 'm2',
      isAutoGenerated: false,
      title: '已确认里程碑',
      description: null,
      date: '2026-05-10T00:00:00.000Z',
      locationName: null,
      photoId: null,
      photo: null,
    },
  ])

  assert.equal(sections.pending.length, 1)
  assert.equal(sections.confirmed.length, 1)
  assert.equal(sections.hasPending, true)
})

test('buildMilestoneRecommendationReason explains why an AI candidate is worth reviewing', () => {
  assert.equal(
    buildMilestoneRecommendationReason({
      isAutoGenerated: true,
      locationName: '厦门',
      photoId: 'photo_1',
    }),
    '这条候选同时关联了地点和照片，适合作为一段回忆的清晰节点。'
  )

  assert.equal(
    buildMilestoneRecommendationReason({
      isAutoGenerated: true,
      locationName: null,
      photoId: null,
    }),
    '这条候选把一张可能重要的时刻提前提了出来，适合你快速确认是否值得留在时间线里。'
  )
})

test('buildTimelineMergeSuggestions finds nearby milestones with the same location', () => {
  const suggestions = buildTimelineMergeSuggestions([
    {
      id: 'm1',
      isAutoGenerated: false,
      title: '第一次去厦门',
      description: null,
      date: '2026-05-20T00:00:00.000Z',
      locationName: '厦门',
      photoId: null,
      photo: null,
    },
    {
      id: 'm2',
      isAutoGenerated: false,
      title: '厦门海边散步',
      description: null,
      date: '2026-05-22T00:00:00.000Z',
      locationName: '厦门',
      photoId: null,
      photo: null,
    },
    {
      id: 'm3',
      isAutoGenerated: false,
      title: '广州日常',
      description: null,
      date: '2026-06-10T00:00:00.000Z',
      locationName: '广州',
      photoId: null,
      photo: null,
    },
  ])

  assert.deepEqual(suggestions, [
    {
      primaryId: 'm1',
      primaryTitle: '第一次去厦门',
      duplicateId: 'm2',
      duplicateTitle: '厦门海边散步',
      locationName: '厦门',
      dateGapDays: 2,
    },
  ])
})

test('buildTimelinePreviewItems keeps only milestones with previewable photos in timeline order', () => {
  assert.deepEqual(
    buildTimelinePreviewItems([
      {
        id: 'm1',
        title: '第一次见面',
        description: null,
        date: '2026-05-20T00:00:00.000Z',
        locationName: null,
        isAutoGenerated: false,
        photo: {
          id: 'p1',
          thumbnailUrl: 'https://cdn.example.com/1-thumb.jpg',
          displayUrl: 'https://cdn.example.com/1.jpg',
        },
      },
      {
        id: 'm2',
        title: '第二次见面',
        description: null,
        date: '2026-05-22T00:00:00.000Z',
        locationName: null,
        isAutoGenerated: false,
        photo: {
          id: 'p2',
          thumbnailUrl: null,
          displayUrl: null,
        },
      },
    ]),
    [
      {
        id: 'p1',
        src: 'https://cdn.example.com/1.jpg',
        alt: '第一次见面',
        title: '第一次见面',
      },
    ]
  )
})

test('buildDashboardTimelinePreviewItems builds preview items from dashboard milestone photos', () => {
  assert.deepEqual(
    buildDashboardTimelinePreviewItems([
      {
        id: 'm1',
        title: '雪山湖畔的承诺',
        description: null,
        date: '2026-09-03T00:00:00.000Z',
        locationName: null,
        isAutoGenerated: false,
        photoId: 'p1',
        photo: { thumbnailUrl: 'https://cdn.example.com/1-thumb.jpg' },
      },
      {
        id: 'm2',
        title: '没有图片',
        description: null,
        date: '2026-09-04T00:00:00.000Z',
        locationName: null,
        isAutoGenerated: false,
        photoId: null,
        photo: null,
      },
    ]),
    [
      {
        id: 'p1',
        src: 'https://cdn.example.com/1-thumb.jpg',
        alt: '雪山湖畔的承诺',
        title: '雪山湖畔的承诺',
      },
    ]
  )
})
