import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { withAuth } from '@/lib/api-middleware'

export const GET = withAuth(async (req, { coupleUser }) => {
  const milestones = await prisma.milestone.findMany({
    where: { coupleId: coupleUser.coupleId },
    orderBy: { date: 'asc' },
    include: { photo: { select: { thumbnailUrl: true } } },
  })
  return NextResponse.json({ milestones })
})

export const POST = withAuth(async (req, { coupleUser }) => {
  const { title, description, date, locationName, photoId } = await req.json()
  if (!title || !date) {
    return NextResponse.json({ error: 'Title and date required' }, { status: 400 })
  }

  const milestone = await prisma.milestone.create({
    data: {
      coupleId: coupleUser.coupleId,
      title,
      description,
      date: new Date(date),
      locationName,
      photoId,
      isAutoGenerated: false,
    },
  })
  return NextResponse.json(milestone, { status: 201 })
})
